INSERT INTO Category VALUES (DEFAULT, 'Vendetta');
INSERT INTO Category VALUES (DEFAULT, 'Drama');
INSERT INTO Category VALUES (DEFAULT, 'Whaling');
INSERT INTO Category VALUES (DEFAULT, 'Fiction');
INSERT INTO Category VALUES (DEFAULT, 'Humorous stories');
INSERT INTO Category VALUES (DEFAULT, 'Italy');
INSERT INTO Category VALUES (DEFAULT, 'Didactic fiction');
INSERT INTO Category VALUES (DEFAULT, 'Autobiographical fiction');
INSERT INTO Category VALUES (DEFAULT, 'New England');
INSERT INTO Category VALUES (DEFAULT, 'English drama');
INSERT INTO Category VALUES (DEFAULT, 'Early modern and Elizabethan, 1500-1600');
INSERT INTO Category VALUES (DEFAULT, 'Love stories');
INSERT INTO Category VALUES (DEFAULT, 'Self-actualization (Psychology)');
INSERT INTO Category VALUES (DEFAULT, 'History');
INSERT INTO Category VALUES (DEFAULT, '1914-1945');
INSERT INTO Category VALUES (DEFAULT, 'England');
INSERT INTO Category VALUES (DEFAULT, 'Gothic fiction');
INSERT INTO Category VALUES (DEFAULT, 'Epistolary fiction');
INSERT INTO Category VALUES (DEFAULT, 'Sea stories');
INSERT INTO Category VALUES (DEFAULT, 'France');
INSERT INTO Category VALUES (DEFAULT, 'Louis XIV, 1643-1715');
INSERT INTO Category VALUES (DEFAULT, 'Wagner, Richard, 1813-1883');
INSERT INTO Category VALUES (DEFAULT, 'Germany');
INSERT INTO Category VALUES (DEFAULT, 'Biography');
INSERT INTO Category VALUES (DEFAULT, 'Science fiction');
INSERT INTO Category VALUES (DEFAULT, 'Historical fiction');
INSERT INTO Category VALUES (DEFAULT, '1812-1898');
INSERT INTO Category VALUES (DEFAULT, 'Fantasy fiction');
INSERT INTO Category VALUES (DEFAULT, 'Juvenile fiction');
INSERT INTO Category VALUES (DEFAULT, 'Nationalists');
INSERT INTO Category VALUES (DEFAULT, 'Philippines');
INSERT INTO Category VALUES (DEFAULT, 'Translations into Tagalog');
INSERT INTO Category VALUES (DEFAULT, 'Psychological fiction');
INSERT INTO Category VALUES (DEFAULT, 'Comedies');
INSERT INTO Category VALUES (DEFAULT, 'Victoria, 1837-1901');
INSERT INTO Category VALUES (DEFAULT, '1800-1950');
INSERT INTO Category VALUES (DEFAULT, 'Horror tales');
INSERT INTO Category VALUES (DEFAULT, 'Revolution, 1789-1799');
INSERT INTO Category VALUES (DEFAULT, '18th century');
INSERT INTO Category VALUES (DEFAULT, 'London');
INSERT INTO Category VALUES (DEFAULT, 'Paris');
INSERT INTO Category VALUES (DEFAULT, '1789-1799');
INSERT INTO Category VALUES (DEFAULT, 'Marriage');
INSERT INTO Category VALUES (DEFAULT, 'Translations into English');
INSERT INTO Category VALUES (DEFAULT, 'Orphans');
INSERT INTO Category VALUES (DEFAULT, 'Psychology');
INSERT INTO Category VALUES (DEFAULT, 'Political satire, English');
INSERT INTO Category VALUES (DEFAULT, 'Politics and government');
INSERT INTO Category VALUES (DEFAULT, 'Humor');
INSERT INTO Category VALUES (DEFAULT, 'Campaigns');
INSERT INTO Category VALUES (DEFAULT, 'Russia');
INSERT INTO Category VALUES (DEFAULT, 'Alexander I, 1801-1825');
INSERT INTO Category VALUES (DEFAULT, 'Holmes, Sherlock (Fictitious character)');
INSERT INTO Category VALUES (DEFAULT, 'Philippine fiction (Spanish)');
INSERT INTO Category VALUES (DEFAULT, 'Social life and customs');
INSERT INTO Category VALUES (DEFAULT, '1533-1917');
INSERT INTO Category VALUES (DEFAULT, '19th century');
INSERT INTO Category VALUES (DEFAULT, 'Adultery');
INSERT INTO Category VALUES (DEFAULT, 'Colonial period, ca. 1600-1775');
INSERT INTO Category VALUES (DEFAULT, 'English language');
INSERT INTO Category VALUES (DEFAULT, 'Slang');
INSERT INTO Category VALUES (DEFAULT, 'Dictionaries');
INSERT INTO Category VALUES (DEFAULT, 'Dialects');
INSERT INTO Category VALUES (DEFAULT, 'Glossaries, vocabularies, etc.');
INSERT INTO Category VALUES (DEFAULT, 'Languages');
INSERT INTO Category VALUES (DEFAULT, 'City and town life');
INSERT INTO Category VALUES (DEFAULT, 'Detective and mystery stories');
INSERT INTO Category VALUES (DEFAULT, 'Psychological aspects');
INSERT INTO Category VALUES (DEFAULT, 'Classical literature');
INSERT INTO Category VALUES (DEFAULT, 'Poetry');
INSERT INTO Category VALUES (DEFAULT, 'Tagalog poetry');
INSERT INTO Category VALUES (DEFAULT, 'Fairy tales');
INSERT INTO Category VALUES (DEFAULT, 'State, The');
INSERT INTO Category VALUES (DEFAULT, 'Early works to 1800');
INSERT INTO Category VALUES (DEFAULT, 'Philosophy');
INSERT INTO Category VALUES (DEFAULT, 'Love');
INSERT INTO Category VALUES (DEFAULT, 'Homer');
INSERT INTO Category VALUES (DEFAULT, 'Spain');
INSERT INTO Category VALUES (DEFAULT, '16th century');
INSERT INTO Category VALUES (DEFAULT, 'Christmas stories');
INSERT INTO Category VALUES (DEFAULT, 'Oz (Imaginary place)');
INSERT INTO Category VALUES (DEFAULT, 'Ethics');
INSERT INTO Category VALUES (DEFAULT, 'Stoics');
INSERT INTO Category VALUES (DEFAULT, 'Incest');
INSERT INTO Category VALUES (DEFAULT, 'African Americans');
INSERT INTO Category VALUES (DEFAULT, 'Prince Edward Island');
INSERT INTO Category VALUES (DEFAULT, '20th century');
INSERT INTO Category VALUES (DEFAULT, '1867-1914');
INSERT INTO Category VALUES (DEFAULT, 'Revenge');
INSERT INTO Category VALUES (DEFAULT, 'Shipwreck victims');
INSERT INTO Category VALUES (DEFAULT, 'Mysticism');
INSERT INTO Category VALUES (DEFAULT, 'Africa');
INSERT INTO Category VALUES (DEFAULT, 'Fantasy literature');
INSERT INTO Category VALUES (DEFAULT, 'Civil disobedience');
INSERT INTO Category VALUES (DEFAULT, 'Homes and haunts');
INSERT INTO Category VALUES (DEFAULT, 'Massachusetts');
INSERT INTO Category VALUES (DEFAULT, 'Walden Woods');
INSERT INTO Category VALUES (DEFAULT, 'Epic poetry, Italian');
INSERT INTO Category VALUES (DEFAULT, 'To 1400');
INSERT INTO Category VALUES (DEFAULT, 'Words and phrase lists');
INSERT INTO Category VALUES (DEFAULT, 'English');
INSERT INTO Category VALUES (DEFAULT, 'Superman (Philosophical concept)');
INSERT INTO Category VALUES (DEFAULT, 'Short stories');
INSERT INTO Category VALUES (DEFAULT, 'Toys');
INSERT INTO Category VALUES (DEFAULT, 'Gautama Buddha');
INSERT INTO Category VALUES (DEFAULT, 'Religion');
INSERT INTO Category VALUES (DEFAULT, 'Political science');
INSERT INTO Category VALUES (DEFAULT, 'Political fiction');
INSERT INTO Category VALUES (DEFAULT, '1801-1917');
INSERT INTO Category VALUES (DEFAULT, 'Officials and employees');
INSERT INTO Category VALUES (DEFAULT, 'Young men');
INSERT INTO Category VALUES (DEFAULT, 'Travel');
INSERT INTO Category VALUES (DEFAULT, 'Thames River');
INSERT INTO Category VALUES (DEFAULT, 'Folklore');
INSERT INTO Category VALUES (DEFAULT, 'India');
INSERT INTO Category VALUES (DEFAULT, 'Knowledge, Theory of');
INSERT INTO Category VALUES (DEFAULT, 'Introductions');
INSERT INTO Category VALUES (DEFAULT, 'Dogs');
INSERT INTO Category VALUES (DEFAULT, 'Augustine, Saint, Bishop of Hippo');
INSERT INTO Category VALUES (DEFAULT, 'Algeria');
INSERT INTO Category VALUES (DEFAULT, 'Hippo (Extinct city)');
INSERT INTO Category VALUES (DEFAULT, 'Bishops');
INSERT INTO Category VALUES (DEFAULT, 'Bible');
INSERT INTO Category VALUES (DEFAULT, 'Short stories, American');
INSERT INTO Category VALUES (DEFAULT, 'Dexter, Timothy, 1747-1806');
INSERT INTO Category VALUES (DEFAULT, 'French essays');
INSERT INTO Category VALUES (DEFAULT, 'Private investigators');
INSERT INTO Category VALUES (DEFAULT, 'Investigation');
INSERT INTO Category VALUES (DEFAULT, 'Shipwreck survival');
INSERT INTO Category VALUES (DEFAULT, 'Military art and science');
INSERT INTO Category VALUES (DEFAULT, 'Young women');
INSERT INTO Category VALUES (DEFAULT, 'Slavery');
INSERT INTO Category VALUES (DEFAULT, 'Ghosts');
INSERT INTO Category VALUES (DEFAULT, '1775-1865');
INSERT INTO Category VALUES (DEFAULT, 'Sabotage');
INSERT INTO Category VALUES (DEFAULT, 'Epic poetry, English (Old)');
INSERT INTO Category VALUES (DEFAULT, 'Mythology');
INSERT INTO Category VALUES (DEFAULT, 'Jews');
INSERT INTO Category VALUES (DEFAULT, 'Antiquities');
INSERT INTO Category VALUES (DEFAULT, 'Douglass, Frederick, 1818-1895');
INSERT INTO Category VALUES (DEFAULT, 'United States');
INSERT INTO Category VALUES (DEFAULT, 'Conduct of life');
INSERT INTO Category VALUES (DEFAULT, 'Fall of man');
INSERT INTO Category VALUES (DEFAULT, 'History of Biblical events');
INSERT INTO Category VALUES (DEFAULT, 'History and criticism');
INSERT INTO Category VALUES (DEFAULT, 'Rhetoric');
INSERT INTO Category VALUES (DEFAULT, 'Style');
INSERT INTO Category VALUES (DEFAULT, 'Tragedies');
INSERT INTO Category VALUES (DEFAULT, 'Kings and rulers');
INSERT INTO Category VALUES (DEFAULT, 'Latin language');
INSERT INTO Category VALUES (DEFAULT, 'Readers');
INSERT INTO Category VALUES (DEFAULT, 'Etiquette');
INSERT INTO Category VALUES (DEFAULT, 'Juan, Don (Legendary character)');
INSERT INTO Category VALUES (DEFAULT, 'Satire');
INSERT INTO Category VALUES (DEFAULT, 'Franklin, Benjamin, 1706-1790');
INSERT INTO Category VALUES (DEFAULT, 'Succession');
INSERT INTO Category VALUES (DEFAULT, 'Death');
INSERT INTO Category VALUES (DEFAULT, 'Arthurian romances');
INSERT INTO Category VALUES (DEFAULT, 'Legends');
INSERT INTO Category VALUES (DEFAULT, 'Erotic stories');
INSERT INTO Category VALUES (DEFAULT, 'Children');
INSERT INTO Category VALUES (DEFAULT, 'Socialism');
INSERT INTO Category VALUES (DEFAULT, 'Rome');
INSERT INTO Category VALUES (DEFAULT, 'Empire, 30 B.C.-476 A.D.');
INSERT INTO Category VALUES (DEFAULT, 'To 527');
INSERT INTO Category VALUES (DEFAULT, 'Success');
INSERT INTO Category VALUES (DEFAULT, 'New Thought');
INSERT INTO Category VALUES (DEFAULT, 'Enslaved persons');
INSERT INTO Category VALUES (DEFAULT, 'Great Britain');
INSERT INTO Category VALUES (DEFAULT, 'Louisiana');
INSERT INTO Category VALUES (DEFAULT, 'New Orleans');
INSERT INTO Category VALUES (DEFAULT, 'Social conditions');
INSERT INTO Category VALUES (DEFAULT, 'Liberty');
INSERT INTO Category VALUES (DEFAULT, 'Wolfdogs');
INSERT INTO Category VALUES (DEFAULT, 'Education');
INSERT INTO Category VALUES (DEFAULT, 'Social aspects');
INSERT INTO Category VALUES (DEFAULT, 'English poetry');
INSERT INTO Category VALUES (DEFAULT, 'Europe');
INSERT INTO Category VALUES (DEFAULT, 'Epic literature, Sanskrit');
INSERT INTO Category VALUES (DEFAULT, 'Louis XIII, 1610-1643');
INSERT INTO Category VALUES (DEFAULT, 'Appreciation');
INSERT INTO Category VALUES (DEFAULT, 'Economic aspects');
INSERT INTO Category VALUES (DEFAULT, 'Apocryphal books (Old Testament)');
INSERT INTO Category VALUES (DEFAULT, 'Adventure stories');
INSERT INTO Category VALUES (DEFAULT, 'Cebuano language');
INSERT INTO Category VALUES (DEFAULT, 'Hell');
INSERT INTO Category VALUES (DEFAULT, 'Pastoral poetry');
INSERT INTO Category VALUES (DEFAULT, 'Evolution (Biology)');
INSERT INTO Category VALUES (DEFAULT, 'Cyrano de Bergerac, 1619-1655');
INSERT INTO Category VALUES (DEFAULT, '17th century');
INSERT INTO Category VALUES (DEFAULT, 'American drama');
INSERT INTO Category VALUES (DEFAULT, 'French poetry');
INSERT INTO Category VALUES (DEFAULT, '1775-1783');
INSERT INTO Category VALUES (DEFAULT, 'Allegories');
INSERT INTO Category VALUES (DEFAULT, 'Enslaved women');
INSERT INTO Category VALUES (DEFAULT, 'Meat industry and trade');
INSERT INTO Category VALUES (DEFAULT, 'Economics');
INSERT INTO Category VALUES (DEFAULT, 'Early modern, 1500-1700');
INSERT INTO Category VALUES (DEFAULT, 'London (England)');
INSERT INTO Category VALUES (DEFAULT, 'Denmark');
INSERT INTO Category VALUES (DEFAULT, 'Families');
INSERT INTO Category VALUES (DEFAULT, 'Greece');
INSERT INTO Category VALUES (DEFAULT, 'Peloponnesian War, 431-404 B.C.');
INSERT INTO Category VALUES (DEFAULT, 'German poetry');
INSERT INTO Category VALUES (DEFAULT, 'Cooking, Roman');
INSERT INTO Category VALUES (DEFAULT, 'Christian pilgrims and pilgrimages');
INSERT INTO Category VALUES (DEFAULT, 'Wilde, Oscar, 1854-1900');
INSERT INTO Category VALUES (DEFAULT, 'Collection and preservation');
INSERT INTO Category VALUES (DEFAULT, 'Maxims');
INSERT INTO Category VALUES (DEFAULT, 'Apologetics');
INSERT INTO Category VALUES (DEFAULT, 'Short stories, French');
INSERT INTO Category VALUES (DEFAULT, 'Philosophy and religion');
INSERT INTO Category VALUES (DEFAULT, 'Americans');
INSERT INTO Category VALUES (DEFAULT, 'Alfonso XIII, 1886-1931');
INSERT INTO Category VALUES (DEFAULT, 'Middle East');
INSERT INTO Category VALUES (DEFAULT, 'Description and travel');
INSERT INTO Category VALUES (DEFAULT, 'Semantics');
INSERT INTO Category VALUES (DEFAULT, 'Societies and clubs');
INSERT INTO Category VALUES (DEFAULT, 'Formulas, recipes, etc.');
INSERT INTO Category VALUES (DEFAULT, 'Handbooks, manuals, etc.');
INSERT INTO Category VALUES (DEFAULT, 'Christianity');
INSERT INTO Category VALUES (DEFAULT, 'Controversial literature');
INSERT INTO Category VALUES (DEFAULT, 'Seventh-Day Adventists');
INSERT INTO Category VALUES (DEFAULT, 'Doctrines');
INSERT INTO Category VALUES (DEFAULT, 'Social psychology');
INSERT INTO Category VALUES (DEFAULT, 'Early works to 1900');
INSERT INTO Category VALUES (DEFAULT, 'American poetry');
INSERT INTO Category VALUES (DEFAULT, 'Russian fiction');
INSERT INTO Category VALUES (DEFAULT, 'Essays');
INSERT INTO Category VALUES (DEFAULT, 'History, Ancient');
INSERT INTO Category VALUES (DEFAULT, 'To 146 B.C.');
INSERT INTO Category VALUES (DEFAULT, 'Louis XI, 1461-1483');
INSERT INTO Category VALUES (DEFAULT, 'To 1515');
INSERT INTO Category VALUES (DEFAULT, 'Portuguese language');
INSERT INTO Category VALUES (DEFAULT, 'Rabbits');
INSERT INTO Category VALUES (DEFAULT, 'Ireland');
INSERT INTO Category VALUES (DEFAULT, 'Plague');
INSERT INTO Category VALUES (DEFAULT, 'Arab countries');
INSERT INTO Category VALUES (DEFAULT, 'Short stories, Russian');
INSERT INTO Category VALUES (DEFAULT, 'Core');
INSERT INTO Category VALUES (DEFAULT, 'Civil War, 1861-1865');
INSERT INTO Category VALUES (DEFAULT, 'Persian poetry');
INSERT INTO Category VALUES (DEFAULT, 'Synonyms and antonyms');
INSERT INTO Category VALUES (DEFAULT, 'Aeneas (Legendary character)');
INSERT INTO Author VALUES (DEFAULT, 'William Shakespeare');
INSERT INTO Author VALUES (DEFAULT, 'Herman Melville');
INSERT INTO Author VALUES (DEFAULT, 'E. M. Forster');
INSERT INTO Author VALUES (DEFAULT, 'George Eliot');
INSERT INTO Author VALUES (DEFAULT, 'Louisa May Alcott');
INSERT INTO Author VALUES (DEFAULT, 'Elizabeth Von Arnim');
INSERT INTO Author VALUES (DEFAULT, 'L. M. Montgomery');
INSERT INTO Author VALUES (DEFAULT, 'Elizabeth Cleghorn Gaskell');
INSERT INTO Author VALUES (DEFAULT, 'T. Smollett');
INSERT INTO Author VALUES (DEFAULT, 'Henry Fielding');
INSERT INTO Author VALUES (DEFAULT, 'Alexandre Dumas');
INSERT INTO Author VALUES (DEFAULT, 'Richard Wagner');
INSERT INTO Author VALUES (DEFAULT, 'Mary Wollstonecraft Shelley');
INSERT INTO Author VALUES (DEFAULT, 'Jane Austen');
INSERT INTO Author VALUES (DEFAULT, 'José Rizal');
INSERT INTO Author VALUES (DEFAULT, 'Lewis Carroll');
INSERT INTO Author VALUES (DEFAULT, 'F. Scott Fitzgerald');
INSERT INTO Author VALUES (DEFAULT, 'Oscar Wilde');
INSERT INTO Author VALUES (DEFAULT, 'Bram Stoker');
INSERT INTO Author VALUES (DEFAULT, 'Charles Dickens');
INSERT INTO Author VALUES (DEFAULT, 'Henrik Ibsen');
INSERT INTO Author VALUES (DEFAULT, 'Franz Kafka');
INSERT INTO Author VALUES (DEFAULT, 'Robert Louis Stevenson');
INSERT INTO Author VALUES (DEFAULT, 'Charlotte Perkins Gilman');
INSERT INTO Author VALUES (DEFAULT, 'Jonathan Swift');
INSERT INTO Author VALUES (DEFAULT, 'graf Leo Tolstoy');
INSERT INTO Author VALUES (DEFAULT, 'Arthur Conan Doyle');
INSERT INTO Author VALUES (DEFAULT, 'Fyodor Dostoyevsky');
INSERT INTO Author VALUES (DEFAULT, 'Nathaniel Hawthorne');
INSERT INTO Author VALUES (DEFAULT, 'John Camden Hotten');
INSERT INTO Author VALUES (DEFAULT, 'Mark Twain');
INSERT INTO Author VALUES (DEFAULT, 'James Joyce');
INSERT INTO Author VALUES (DEFAULT, 'Homer');
INSERT INTO Author VALUES (DEFAULT, 'Francisco Balagtas');
INSERT INTO Author VALUES (DEFAULT, 'Charlotte Brontë');
INSERT INTO Author VALUES (DEFAULT, 'Jacob Grimm and Wilhelm Grimm');
INSERT INTO Author VALUES (DEFAULT, 'Niccolò Machiavelli');
INSERT INTO Author VALUES (DEFAULT, 'Vatsyayana');
INSERT INTO Author VALUES (DEFAULT, 'Miguel de Cervantes Saavedra');
INSERT INTO Author VALUES (DEFAULT, 'L. Frank Baum');
INSERT INTO Author VALUES (DEFAULT, 'Friedrich Wilhelm Nietzsche');
INSERT INTO Author VALUES (DEFAULT, 'Emperor of Rome Marcus Aurelius');
INSERT INTO Author VALUES (DEFAULT, 'Anonymous');
INSERT INTO Author VALUES (DEFAULT, 'W. E. B. Du Bois');
INSERT INTO Author VALUES (DEFAULT, 'Emily Brontë');
INSERT INTO Author VALUES (DEFAULT, 'Kahlil Gibran');
INSERT INTO Author VALUES (DEFAULT, 'Joseph Conrad');
INSERT INTO Author VALUES (DEFAULT, 'J. M. Barrie');
INSERT INTO Author VALUES (DEFAULT, 'Henry David Thoreau');
INSERT INTO Author VALUES (DEFAULT, 'Dante Alighieri');
INSERT INTO Author VALUES (DEFAULT, 'H. G. Wells');
INSERT INTO Author VALUES (DEFAULT, 'Plato');
INSERT INTO Author VALUES (DEFAULT, 'Grady Ward');
INSERT INTO Author VALUES (DEFAULT, 'A. A. Milne');
INSERT INTO Author VALUES (DEFAULT, 'Hermann Hesse');
INSERT INTO Author VALUES (DEFAULT, 'Victor Hugo');
INSERT INTO Author VALUES (DEFAULT, 'Rudyard Kipling');
INSERT INTO Author VALUES (DEFAULT, 'Thomas Hobbes');
INSERT INTO Author VALUES (DEFAULT, 'Christopher Marlowe');
INSERT INTO Author VALUES (DEFAULT, 'Bernard Shaw');
INSERT INTO Author VALUES (DEFAULT, 'Jerome K. Jerome');
INSERT INTO Author VALUES (DEFAULT, 'Valmiki');
INSERT INTO Author VALUES (DEFAULT, 'Bertrand Russell');
INSERT INTO Author VALUES (DEFAULT, 'Jack London');
INSERT INTO Author VALUES (DEFAULT, 'Bishop of Hippo Saint Augustine');
INSERT INTO Author VALUES (DEFAULT, 'Robert W. Chambers');
INSERT INTO Author VALUES (DEFAULT, 'Timothy Dexter');
INSERT INTO Author VALUES (DEFAULT, 'John Locke');
INSERT INTO Author VALUES (DEFAULT, 'Michel de Montaigne');
INSERT INTO Author VALUES (DEFAULT, 'Agatha Christie');
INSERT INTO Author VALUES (DEFAULT, 'Daniel Defoe');
INSERT INTO Author VALUES (DEFAULT, 'active 6th century B.C. Sunzi');
INSERT INTO Author VALUES (DEFAULT, 'Joseph Sheridan Le Fanu');
INSERT INTO Author VALUES (DEFAULT, 'Harriet Beecher Stowe');
INSERT INTO Author VALUES (DEFAULT, 'Washington Irving');
INSERT INTO Author VALUES (DEFAULT, 'Edgar Allan Poe');
INSERT INTO Author VALUES (DEFAULT, 'United States. Office of Strategic Services');
INSERT INTO Author VALUES (DEFAULT, 'Frances Hodgson Burnett');
INSERT INTO Author VALUES (DEFAULT, 'Moncure Daniel Conway');
INSERT INTO Author VALUES (DEFAULT, 'Ayn Rand');
INSERT INTO Author VALUES (DEFAULT, 'Jules Verne');
INSERT INTO Author VALUES (DEFAULT, 'Flavius Josephus');
INSERT INTO Author VALUES (DEFAULT, 'Frederick Douglass');
INSERT INTO Author VALUES (DEFAULT, 'Epictetus');
INSERT INTO Author VALUES (DEFAULT, 'John Milton');
INSERT INTO Author VALUES (DEFAULT, 'F. Max Müller');
INSERT INTO Author VALUES (DEFAULT, 'William Strunk');
INSERT INTO Author VALUES (DEFAULT, 'Edmund Luce');
INSERT INTO Author VALUES (DEFAULT, 'Baron George Gordon Byron Byron');
INSERT INTO Author VALUES (DEFAULT, 'Voltaire');
INSERT INTO Author VALUES (DEFAULT, 'Benjamin Franklin');
INSERT INTO Author VALUES (DEFAULT, 'Immanuel Kant');
INSERT INTO Author VALUES (DEFAULT, 'Sir Thomas Malory');
INSERT INTO Author VALUES (DEFAULT, 'Aristotle');
INSERT INTO Author VALUES (DEFAULT, 'Felix Salten');
INSERT INTO Author VALUES (DEFAULT, 'Heinrich Hoffmann');
INSERT INTO Author VALUES (DEFAULT, 'Karl Marx and Friedrich Engels');
INSERT INTO Author VALUES (DEFAULT, 'Johann Wolfgang von Goethe');
INSERT INTO Author VALUES (DEFAULT, 'Edward Gibbon');
INSERT INTO Author VALUES (DEFAULT, 'P. T. Barnum');
INSERT INTO Author VALUES (DEFAULT, 'Henry James');
INSERT INTO Author VALUES (DEFAULT, 'James Allen');
INSERT INTO Author VALUES (DEFAULT, 'Olaudah Equiano');
INSERT INTO Author VALUES (DEFAULT, 'Kate Chopin');
INSERT INTO Author VALUES (DEFAULT, 'John Stuart Mill');
INSERT INTO Author VALUES (DEFAULT, 'John Dewey');
INSERT INTO Author VALUES (DEFAULT, 'Kurt Vonnegut');
INSERT INTO Author VALUES (DEFAULT, 'Anton Pavlovich Chekhov');
INSERT INTO Author VALUES (DEFAULT, 'Rutherford Hayes Platt');
INSERT INTO Author VALUES (DEFAULT, 'John U. Wolff');
INSERT INTO Author VALUES (DEFAULT, 'William Blake');
INSERT INTO Author VALUES (DEFAULT, 'Charles Darwin');
INSERT INTO Author VALUES (DEFAULT, 'Benedictus de Spinoza');
INSERT INTO Author VALUES (DEFAULT, 'Gustave Flaubert');
INSERT INTO Author VALUES (DEFAULT, 'Edmond Rostand');
INSERT INTO Author VALUES (DEFAULT, 'Susan Glaspell');
INSERT INTO Author VALUES (DEFAULT, 'Charles Baudelaire');
INSERT INTO Author VALUES (DEFAULT, 'Thomas Paine');
INSERT INTO Author VALUES (DEFAULT, 'Harriet A. Jacobs');
INSERT INTO Author VALUES (DEFAULT, 'Upton Sinclair');
INSERT INTO Author VALUES (DEFAULT, 'Adam Smith');
INSERT INTO Author VALUES (DEFAULT, 'Edmund Spenser');
INSERT INTO Author VALUES (DEFAULT, 'H. C. Andersen');
INSERT INTO Author VALUES (DEFAULT, 'Thucydides');
INSERT INTO Author VALUES (DEFAULT, 'Thomas Hardy');
INSERT INTO Author VALUES (DEFAULT, 'Apicius');
INSERT INTO Author VALUES (DEFAULT, 'Geoffrey Chaucer');
INSERT INTO Author VALUES (DEFAULT, 'John Webster');
INSERT INTO Author VALUES (DEFAULT, 'H. P. Lovecraft');
INSERT INTO Author VALUES (DEFAULT, 'François duc de La Rochefoucauld');
INSERT INTO Author VALUES (DEFAULT, 'Blaise Pascal');
INSERT INTO Author VALUES (DEFAULT, 'Guy de Maupassant');
INSERT INTO Author VALUES (DEFAULT, 'Boethius');
INSERT INTO Author VALUES (DEFAULT, 'Ernest Hemingway');
INSERT INTO Author VALUES (DEFAULT, 'Gaston Leroux');
INSERT INTO Author VALUES (DEFAULT, 'Kenneth Grahame');
INSERT INTO Author VALUES (DEFAULT, 'Ambrose Bierce');
INSERT INTO Author VALUES (DEFAULT, 'Robert E. Howard');
INSERT INTO Author VALUES (DEFAULT, 'Florence Hartley');
INSERT INTO Author VALUES (DEFAULT, 'Ellen Gould Harmon White');
INSERT INTO Author VALUES (DEFAULT, 'Charles Mackay');
INSERT INTO Author VALUES (DEFAULT, 'Walt Whitman');
INSERT INTO Author VALUES (DEFAULT, 'Ralph Waldo Emerson');
INSERT INTO Author VALUES (DEFAULT, 'Herodotus');
INSERT INTO Author VALUES (DEFAULT, 'Oliver Goldsmith');
INSERT INTO Author VALUES (DEFAULT, 'Cândido de Figueiredo');
INSERT INTO Author VALUES (DEFAULT, 'Philip K. Dick');
INSERT INTO Author VALUES (DEFAULT, 'Beatrix Potter');
INSERT INTO Author VALUES (DEFAULT, 'J. M. Synge');
INSERT INTO Author VALUES (DEFAULT, 'Giovanni Boccaccio');
INSERT INTO Author VALUES (DEFAULT, 'John Cleland');
INSERT INTO Author VALUES (DEFAULT, 'David Hume');
INSERT INTO Author VALUES (DEFAULT, 'Stephen Crane');
INSERT INTO Author VALUES (DEFAULT, 'Alexis de Tocqueville');
INSERT INTO Author VALUES (DEFAULT, 'Alexander Pope');
INSERT INTO Author VALUES (DEFAULT, 'Omar Khayyam');
INSERT INTO Author VALUES (DEFAULT, 'Samuel Fallows');
INSERT INTO Author VALUES (DEFAULT, 'John Galsworthy');
INSERT INTO Author VALUES (DEFAULT, 'Virgil');
INSERT INTO Author VALUES (DEFAULT, 'Edgar Rice Burroughs');
INSERT INTO Author VALUES (DEFAULT, 'Carlo Collodi');
INSERT INTO Book VALUES (DEFAULT, 'Romeo and Juliet', 1, '1998-11-01', '1.txt', 112327);
INSERT INTO Book VALUES (DEFAULT, 'Moby Dick; Or, The Whale', 2, '2001-07-01', '2.txt', 95908);
INSERT INTO Book VALUES (DEFAULT, 'A Room with a View', 3, '2001-05-01', '3.txt', 93308);
INSERT INTO Book VALUES (DEFAULT, 'Middlemarch', 4, '1994-07-01', '4.txt', 91429);
INSERT INTO Book VALUES (DEFAULT, 'Little Women; Or, Meg, Jo, Beth, and Amy', 5, '2011-08-16', '5.txt', 85748);
INSERT INTO Book VALUES (DEFAULT, 'The Complete Works of William Shakespeare', 1, '1994-01-01', '6.txt', 85273);
INSERT INTO Book VALUES (DEFAULT, 'The Enchanted April', 6, '2005-07-29', '7.txt', 83378);
INSERT INTO Book VALUES (DEFAULT, 'The Blue Castle: a novel', 7, '2022-05-03', '8.txt', 82135);
INSERT INTO Book VALUES (DEFAULT, 'Cranford', 8, '1996-01-01', '9.txt', 78921);
INSERT INTO Book VALUES (DEFAULT, 'The Adventures of Ferdinand Count Fathom — Complete', 9, '2004-09-09', '10.txt', 78783);
INSERT INTO Book VALUES (DEFAULT, 'The Expedition of Humphry Clinker', 9, '2000-04-01', '11.txt', 77257);
INSERT INTO Book VALUES (DEFAULT, 'History of Tom Jones, a Foundling', 10, '2004-09-01', '12.txt', 76837);
INSERT INTO Book VALUES (DEFAULT, 'The Adventures of Roderick Random', 9, '2003-05-01', '13.txt', 76760);
INSERT INTO Book VALUES (DEFAULT, 'Twenty Years After', 11, '1998-03-01', '14.txt', 73572);
INSERT INTO Book VALUES (DEFAULT, 'My Life — Volume 1', 12, '2004-02-01', '15.txt', 72873);
INSERT INTO Book VALUES (DEFAULT, 'Frankenstein; Or, The Modern Prometheus', 13, '1993-10-01', '16.txt', 55885);
INSERT INTO Book VALUES (DEFAULT, 'Pride and Prejudice', 14, '1998-06-01', '17.txt', 55225);
INSERT INTO Book VALUES (DEFAULT, 'Noli Me Tangere (Tagalog)', 15, '2006-12-30', '18.txt', 36779);
INSERT INTO Book VALUES (DEFAULT, 'Alice''s Adventures in Wonderland', 16, '2008-06-27', '19.txt', 30048);
INSERT INTO Book VALUES (DEFAULT, 'Ang "Filibusterismo" (Karugtóng ng Noli Me Tangere) (Tagalog)', 15, '2014-12-11', '20.txt', 29584);
INSERT INTO Book VALUES (DEFAULT, 'The Great Gatsby', 17, '2021-01-17', '21.txt', 28437);
INSERT INTO Book VALUES (DEFAULT, 'The Importance of Being Earnest: A Trivial Comedy for Serious People', 18, '1997-03-01', '22.txt', 24536);
INSERT INTO Book VALUES (DEFAULT, 'The Picture of Dorian Gray', 18, '1994-10-01', '23.txt', 24314);
INSERT INTO Book VALUES (DEFAULT, 'Dracula', 19, '1995-10-01', '24.txt', 22278);
INSERT INTO Book VALUES (DEFAULT, 'A Tale of Two Cities', 20, '1994-01-01', '25.txt', 21809);
INSERT INTO Book VALUES (DEFAULT, 'A Doll''s House : a play', 21, '2001-03-01', '26.txt', 21547);
INSERT INTO Book VALUES (DEFAULT, 'Metamorphosis', 22, '2005-08-17', '27.txt', 17580);
INSERT INTO Book VALUES (DEFAULT, 'The Strange Case of Dr. Jekyll and Mr. Hyde', 23, '2008-06-27', '28.txt', 16468);
INSERT INTO Book VALUES (DEFAULT, 'Great Expectations', 20, '1998-07-01', '29.txt', 15851);
INSERT INTO Book VALUES (DEFAULT, 'The Yellow Wallpaper', 24, '1999-11-01', '30.txt', 15291);
INSERT INTO Book VALUES (DEFAULT, 'A Modest Proposal', 25, '1997-10-01', '31.txt', 15155);
INSERT INTO Book VALUES (DEFAULT, 'War and Peace', 26, '2001-04-01', '32.txt', 14881);
INSERT INTO Book VALUES (DEFAULT, 'The Adventures of Sherlock Holmes', 27, '1999-03-01', '33.txt', 14555);
INSERT INTO Book VALUES (DEFAULT, 'The Reign of Greed', 15, '2004-01-01', '34.txt', 13853);
INSERT INTO Book VALUES (DEFAULT, 'The Brothers Karamazov', 28, '2009-02-12', '35.txt', 13637);
INSERT INTO Book VALUES (DEFAULT, 'The Count of Monte Cristo, Illustrated', 11, '1998-01-01', '36.txt', 13586);
INSERT INTO Book VALUES (DEFAULT, 'The Scarlet Letter', 29, '2008-05-05', '37.txt', 13515);
INSERT INTO Book VALUES (DEFAULT, 'The slang dictionary :  Etymological, historical and anecdotal', 30, '2013-02-16', '38.txt', 13463);
INSERT INTO Book VALUES (DEFAULT, 'Adventures of Huckleberry Finn', 31, '2004-06-29', '39.txt', 13066);
INSERT INTO Book VALUES (DEFAULT, 'Ulysses', 32, '2003-07-01', '40.txt', 12738);
INSERT INTO Book VALUES (DEFAULT, 'Crime and Punishment', 28, '2006-03-28', '41.txt', 12220);
INSERT INTO Book VALUES (DEFAULT, 'The Iliad', 33, '2004-07-01', '42.txt', 12216);
INSERT INTO Book VALUES (DEFAULT, 'Florante at Laura (Tagalog)', 34, '2005-05-17', '43.txt', 12178);
INSERT INTO Book VALUES (DEFAULT, 'Jane Eyre: An Autobiography', 35, '1998-03-01', '44.txt', 12096);
INSERT INTO Book VALUES (DEFAULT, 'Grimms'' Fairy Tales', 36, '2001-04-01', '45.txt', 11894);
INSERT INTO Book VALUES (DEFAULT, 'The Philippines a Century Hence', 15, '2011-04-18', '46.txt', 11470);
INSERT INTO Book VALUES (DEFAULT, 'The Prince', 37, '2006-02-11', '47.txt', 11104);
INSERT INTO Book VALUES (DEFAULT, 'The Kama Sutra of Vatsyayana', 38, '2009-01-18', '48.txt', 10619);
INSERT INTO Book VALUES (DEFAULT, 'The Odyssey', 33, '1999-04-01', '49.txt', 10539);
INSERT INTO Book VALUES (DEFAULT, 'Don Quixote', 39, '2004-07-27', '50.txt', 10384);
INSERT INTO Book VALUES (DEFAULT, 'Treasure Island', 23, '2006-02-26', '51.txt', 10274);
INSERT INTO Book VALUES (DEFAULT, 'The Adventures of Tom Sawyer, Complete', 31, '2004-07-01', '52.txt', 9867);
INSERT INTO Book VALUES (DEFAULT, 'A Christmas Carol in Prose; Being a Ghost Story of Christmas', 20, '2004-08-11', '53.txt', 9834);
INSERT INTO Book VALUES (DEFAULT, 'The Wonderful Wizard of Oz', 40, '1993-02-01', '54.txt', 9744);
INSERT INTO Book VALUES (DEFAULT, 'Beyond Good and Evil', 41, '2003-08-01', '55.txt', 9730);
INSERT INTO Book VALUES (DEFAULT, 'Meditations', 42, '2001-06-01', '56.txt', 9406);
INSERT INTO Book VALUES (DEFAULT, 'The Romance of Lust: A classic Victorian erotic novel', 43, '2009-10-14', '57.txt', 9324);
INSERT INTO Book VALUES (DEFAULT, 'The Souls of Black Folk', 44, '1996-01-01', '58.txt', 9233);
INSERT INTO Book VALUES (DEFAULT, 'Anne of Green Gables', 7, '2008-06-27', '59.txt', 9206);
INSERT INTO Book VALUES (DEFAULT, 'Wuthering Heights', 45, '1996-12-01', '60.txt', 9032);
INSERT INTO Book VALUES (DEFAULT, 'The Tempest', 1, '2007-10-26', '61.txt', 8955);
INSERT INTO Book VALUES (DEFAULT, 'The Prophet', 46, '2019-01-01', '62.txt', 8650);
INSERT INTO Book VALUES (DEFAULT, 'Heart of Darkness', 47, '2006-01-09', '63.txt', 8446);
INSERT INTO Book VALUES (DEFAULT, 'Peter Pan', 48, '2008-06-25', '64.txt', 8422);
INSERT INTO Book VALUES (DEFAULT, 'Walden, and On The Duty Of Civil Disobedience', 49, '1995-01-01', '65.txt', 8414);
INSERT INTO Book VALUES (DEFAULT, 'The Hound of the Baskervilles', 27, '2001-10-01', '66.txt', 8158);
INSERT INTO Book VALUES (DEFAULT, 'The divine comedy', 50, '2005-09-01', '67.txt', 8138);
INSERT INTO Book VALUES (DEFAULT, 'The War of the Worlds', 51, '2004-10-01', '68.txt', 8135);
INSERT INTO Book VALUES (DEFAULT, 'The Republic', 52, '1998-10-01', '69.txt', 8098);
INSERT INTO Book VALUES (DEFAULT, 'Moby Multiple Language Lists of Common Words', 53, '2002-05-01', '70.txt', 8076);
INSERT INTO Book VALUES (DEFAULT, 'Thus Spake Zarathustra: A Book for All and None', 41, '1999-12-01', '71.txt', 8048);
INSERT INTO Book VALUES (DEFAULT, 'Dubliners', 32, '2001-09-01', '72.txt', 7897);
INSERT INTO Book VALUES (DEFAULT, 'Winnie-the-Pooh', 54, '2022-01-03', '73.txt', 7867);
INSERT INTO Book VALUES (DEFAULT, 'Anna Karenina', 26, '1998-07-01', '74.txt', 7664);
INSERT INTO Book VALUES (DEFAULT, 'A Study in Scarlet', 27, '1995-04-01', '75.txt', 7565);
INSERT INTO Book VALUES (DEFAULT, 'Emma', 14, '1994-08-01', '76.txt', 7433);
INSERT INTO Book VALUES (DEFAULT, 'Little Women', 5, '1996-05-01', '77.txt', 7377);
INSERT INTO Book VALUES (DEFAULT, 'Siddhartha', 55, '2001-02-01', '78.txt', 7199);
INSERT INTO Book VALUES (DEFAULT, 'The Time Machine', 51, '2004-10-02', '79.txt', 7123);
INSERT INTO Book VALUES (DEFAULT, 'Les Misérables', 56, '2008-06-22', '80.txt', 6979);
INSERT INTO Book VALUES (DEFAULT, 'Oliver Twist', 20, '1996-11-01', '81.txt', 6781);
INSERT INTO Book VALUES (DEFAULT, 'Sense and Sensibility', 14, '1994-09-01', '82.txt', 6775);
INSERT INTO Book VALUES (DEFAULT, 'The Jungle Book', 57, '2006-01-16', '83.txt', 6638);
INSERT INTO Book VALUES (DEFAULT, 'Leviathan', 58, '2002-05-01', '84.txt', 6510);
INSERT INTO Book VALUES (DEFAULT, 'The Tragical History of Doctor Faustus', 59, '1997-01-01', '85.txt', 6323);
INSERT INTO Book VALUES (DEFAULT, 'Notes from the Underground', 28, '1996-07-01', '86.txt', 6123);
INSERT INTO Book VALUES (DEFAULT, 'Pygmalion', 60, '2003-03-01', '87.txt', 6021);
INSERT INTO Book VALUES (DEFAULT, 'Three Men in a Boat (To Say Nothing of the Dog)', 61, '1995-08-01', '88.txt', 5962);
INSERT INTO Book VALUES (DEFAULT, 'The Rámáyan of Válmíki, translated into English verse', 62, '2008-03-18', '89.txt', 5954);
INSERT INTO Book VALUES (DEFAULT, 'The Problems of Philosophy', 63, '2004-06-01', '90.txt', 5928);
INSERT INTO Book VALUES (DEFAULT, 'The Call of the Wild', 64, '2008-07-02', '91.txt', 5893);
INSERT INTO Book VALUES (DEFAULT, 'The Confessions of St. Augustine', 65, '2002-06-01', '92.txt', 5858);
INSERT INTO Book VALUES (DEFAULT, 'The King James Version of the Bible', 43, '1989-08-01', '93.txt', 5852);
INSERT INTO Book VALUES (DEFAULT, 'David Copperfield', 20, '1996-12-01', '94.txt', 5716);
INSERT INTO Book VALUES (DEFAULT, 'The King in Yellow', 66, '2005-07-01', '95.txt', 5696);
INSERT INTO Book VALUES (DEFAULT, 'A Pickle for the Knowing Ones', 67, '2013-08-12', '96.txt', 5665);
INSERT INTO Book VALUES (DEFAULT, 'Second Treatise of Government', 68, '2005-01-01', '97.txt', 5627);
INSERT INTO Book VALUES (DEFAULT, 'Essays of Michel de Montaigne — Complete', 69, '2004-10-26', '98.txt', 5573);
INSERT INTO Book VALUES (DEFAULT, 'The murder of Roger Ackroyd', 70, '2022-10-02', '99.txt', 5559);
INSERT INTO Book VALUES (DEFAULT, 'The Life and Adventures of Robinson Crusoe', 71, '1996-05-01', '100.txt', 5536);
INSERT INTO Book VALUES (DEFAULT, 'The Art of War', 72, '1994-05-01', '101.txt', 5535);
INSERT INTO Book VALUES (DEFAULT, 'Carmilla', 73, '2003-11-01', '102.txt', 5405);
INSERT INTO Book VALUES (DEFAULT, 'The Social Cancer: A Complete English Version of Noli Me Tangere', 15, '2004-10-01', '103.txt', 5316);
INSERT INTO Book VALUES (DEFAULT, 'Uncle Tom''s Cabin', 74, '2006-01-13', '104.txt', 5289);
INSERT INTO Book VALUES (DEFAULT, 'Persuasion', 14, '1994-02-01', '105.txt', 5276);
INSERT INTO Book VALUES (DEFAULT, 'The Legend of Sleepy Hollow', 75, '2008-06-27', '106.txt', 5254);
INSERT INTO Book VALUES (DEFAULT, 'The Works of Edgar Allan Poe — Volume 2', 76, '2000-04-01', '107.txt', 5085);
INSERT INTO Book VALUES (DEFAULT, 'A Midsummer Night''s Dream', 1, '1998-11-01', '108.txt', 4972);
INSERT INTO Book VALUES (DEFAULT, 'Simple Sabotage Field Manual', 77, '2008-08-04', '109.txt', 4959);
INSERT INTO Book VALUES (DEFAULT, 'Through the Looking-Glass', 16, '2008-06-25', '110.txt', 4918);
INSERT INTO Book VALUES (DEFAULT, 'Beowulf: An Anglo-Saxon Epic Poem', 43, '2005-07-19', '111.txt', 4863);
INSERT INTO Book VALUES (DEFAULT, 'The Secret Garden', 78, '2005-12-26', '112.txt', 4751);
INSERT INTO Book VALUES (DEFAULT, 'The Happy Prince, and Other Tales', 18, '1997-05-01', '113.txt', 4714);
INSERT INTO Book VALUES (DEFAULT, 'Gulliver''s Travels into Several Remote Nations of the World', 25, '1997-02-01', '114.txt', 4709);
INSERT INTO Book VALUES (DEFAULT, 'Demonology and Devil-lore', 79, '2012-09-06', '115.txt', 4650);
INSERT INTO Book VALUES (DEFAULT, 'A Portrait of the Artist as a Young Man', 32, '2003-07-01', '116.txt', 4545);
INSERT INTO Book VALUES (DEFAULT, 'Anthem', 80, '1998-03-01', '117.txt', 4522);
INSERT INTO Book VALUES (DEFAULT, 'Twenty Thousand Leagues under the Sea', 81, '1994-09-01', '118.txt', 4399);
INSERT INTO Book VALUES (DEFAULT, 'Antiquities of the Jews', 82, '2001-10-01', '119.txt', 4363);
INSERT INTO Book VALUES (DEFAULT, 'The Prince and the Pauper', 31, '2004-07-05', '120.txt', 4347);
INSERT INTO Book VALUES (DEFAULT, 'Narrative of the Life of Frederick Douglass, an American Slave', 83, '2006-01-12', '121.txt', 4338);
INSERT INTO Book VALUES (DEFAULT, 'The Enchiridion', 84, '2014-03-10', '122.txt', 4270);
INSERT INTO Book VALUES (DEFAULT, 'Paradise Lost', 85, '1992-02-01', '123.txt', 4265);
INSERT INTO Book VALUES (DEFAULT, 'India: What can it teach us?', 86, '2007-03-18', '124.txt', 4262);
INSERT INTO Book VALUES (DEFAULT, 'The Elements of Style', 87, '2011-08-18', '125.txt', 4230);
INSERT INTO Book VALUES (DEFAULT, 'Macbeth', 1, '1998-11-01', '126.txt', 4190);
INSERT INTO Book VALUES (DEFAULT, 'The Mysterious Affair at Styles', 70, '1997-03-01', '127.txt', 4176);
INSERT INTO Book VALUES (DEFAULT, 'Helps to Latin Translation at Sight', 88, '2009-05-20', '128.txt', 4168);
INSERT INTO Book VALUES (DEFAULT, 'Early English Meals and Manners', 43, '2008-03-09', '129.txt', 4166);
INSERT INTO Book VALUES (DEFAULT, 'Don Juan', 89, '2007-06-06', '130.txt', 4140);
INSERT INTO Book VALUES (DEFAULT, 'Candide', 90, '2006-11-27', '131.txt', 4097);
INSERT INTO Book VALUES (DEFAULT, 'Autobiography of Benjamin Franklin', 91, '2006-12-28', '132.txt', 4085);
INSERT INTO Book VALUES (DEFAULT, 'Hamlet, Prince of Denmark', 1, '2009-01-10', '133.txt', 4077);
INSERT INTO Book VALUES (DEFAULT, 'The Critique of Pure Reason', 92, '2003-07-01', '134.txt', 4044);
INSERT INTO Book VALUES (DEFAULT, 'Le Morte d''Arthur: Volume 1', 93, '1998-03-01', '135.txt', 4025);
INSERT INTO Book VALUES (DEFAULT, 'The Ethics of Aristotle', 94, '2005-07-01', '136.txt', 4000);
INSERT INTO Book VALUES (DEFAULT, 'Josefine Mutzenbacher (German)', 95, '2010-02-15', '137.txt', 3939);
INSERT INTO Book VALUES (DEFAULT, 'Struwwelpeter: Merry Stories and Funny Pictures', 96, '2004-04-01', '138.txt', 3919);
INSERT INTO Book VALUES (DEFAULT, 'The Communist Manifesto', 97, '2005-01-25', '139.txt', 3907);
INSERT INTO Book VALUES (DEFAULT, 'The Sorrows of Young Werther', 98, '2001-02-01', '140.txt', 3882);
INSERT INTO Book VALUES (DEFAULT, 'The History of the Decline and Fall of the Roman Empire', 99, '2008-06-07', '141.txt', 3827);
INSERT INTO Book VALUES (DEFAULT, 'The Art of Money Getting; Or, Golden Rules for Making Money', 100, '2005-07-01', '142.txt', 3822);
INSERT INTO Book VALUES (DEFAULT, 'The Turn of the Screw', 101, '1995-02-01', '143.txt', 3801);
INSERT INTO Book VALUES (DEFAULT, 'As a Man Thinketh', 102, '2003-10-01', '144.txt', 3787);
INSERT INTO Book VALUES (DEFAULT, 'The Interesting Narrative of the Life of Olaudah Equiano, Or Gustavus Vassa, The African', 103, '2005-03-17', '145.txt', 3761);
INSERT INTO Book VALUES (DEFAULT, 'The Awakening, and Selected Short Stories', 104, '2006-03-11', '146.txt', 3717);
INSERT INTO Book VALUES (DEFAULT, 'Hard Times', 20, '1997-01-01', '147.txt', 3659);
INSERT INTO Book VALUES (DEFAULT, 'On Liberty', 105, '2011-01-10', '148.txt', 3610);
INSERT INTO Book VALUES (DEFAULT, 'Hamlet, Prince of Denmark', 1, '1998-11-01', '149.txt', 3585);
INSERT INTO Book VALUES (DEFAULT, 'Frankenstein; Or, The Modern Prometheus', 13, '2013-03-13', '150.txt', 3568);
INSERT INTO Book VALUES (DEFAULT, 'White Fang', 64, '1997-05-01', '151.txt', 3541);
INSERT INTO Book VALUES (DEFAULT, 'Democracy and Education: An Introduction to the Philosophy of Education', 106, '1997-03-01', '152.txt', 3527);
INSERT INTO Book VALUES (DEFAULT, 'Childe Harold''s Pilgrimage', 89, '2004-02-01', '153.txt', 3507);
INSERT INTO Book VALUES (DEFAULT, 'The Idiot', 28, '2001-05-01', '154.txt', 3472);
INSERT INTO Book VALUES (DEFAULT, 'The Mahabharata of Krishna-Dwaipayana Vyasa, Volume 1', 43, '2005-03-26', '155.txt', 3468);
INSERT INTO Book VALUES (DEFAULT, 'The Three Musketeers', 11, '1998-03-01', '156.txt', 3455);
INSERT INTO Book VALUES (DEFAULT, '2 B R 0 2 B', 107, '2007-05-03', '157.txt', 3447);
INSERT INTO Book VALUES (DEFAULT, 'The Sign of the Four', 27, '2000-03-01', '158.txt', 3443);
INSERT INTO Book VALUES (DEFAULT, 'Northanger Abbey', 14, '1994-04-01', '159.txt', 3440);
INSERT INTO Book VALUES (DEFAULT, 'The Sea-Gull', 108, '2006-02-22', '160.txt', 3413);
INSERT INTO Book VALUES (DEFAULT, 'Symposium', 52, '1999-01-01', '161.txt', 3352);
INSERT INTO Book VALUES (DEFAULT, 'The First Book of Adam and Eve', 109, '1996-01-01', '162.txt', 3348);
INSERT INTO Book VALUES (DEFAULT, 'Around the World in Eighty Days', 81, '1994-01-01', '163.txt', 3331);
INSERT INTO Book VALUES (DEFAULT, 'A Dictionary of Cebuano Visayan', 110, '2012-06-24', '164.txt', 3295);
INSERT INTO Book VALUES (DEFAULT, 'Don Quijote (Spanish)', 39, '1999-12-01', '165.txt', 3276);
INSERT INTO Book VALUES (DEFAULT, 'Just So Stories', 57, '2001-08-01', '166.txt', 3231);
INSERT INTO Book VALUES (DEFAULT, 'Divine Comedy, Longfellow''s Translation, Hell', 50, '1997-08-01', '167.txt', 3219);
INSERT INTO Book VALUES (DEFAULT, 'Songs of Innocence and of Experience', 111, '1999-10-01', '168.txt', 3181);
INSERT INTO Book VALUES (DEFAULT, 'On the Origin of Species By Means of Natural Selection', 112, '1998-03-01', '169.txt', 3175);
INSERT INTO Book VALUES (DEFAULT, 'Ethics', 113, '2003-02-01', '170.txt', 3168);
INSERT INTO Book VALUES (DEFAULT, 'Madame Bovary', 114, '2006-02-26', '171.txt', 3156);
INSERT INTO Book VALUES (DEFAULT, 'The Genealogy of Morals', 41, '2016-06-13', '172.txt', 3139);
INSERT INTO Book VALUES (DEFAULT, 'Cyrano de Bergerac', 115, '1998-03-01', '173.txt', 3083);
INSERT INTO Book VALUES (DEFAULT, 'Much Ado about Nothing', 1, '1998-11-01', '174.txt', 3076);
INSERT INTO Book VALUES (DEFAULT, 'Plays', 116, '2004-01-01', '175.txt', 3068);
INSERT INTO Book VALUES (DEFAULT, 'The Flowers of Evil', 117, '2011-05-13', '176.txt', 3054);
INSERT INTO Book VALUES (DEFAULT, 'Common Sense', 118, '1994-07-01', '177.txt', 3049);
INSERT INTO Book VALUES (DEFAULT, 'The Trial', 22, '2005-04-01', '178.txt', 3044);
INSERT INTO Book VALUES (DEFAULT, 'The Invisible Man: A Grotesque Romance', 51, '2004-03-01', '179.txt', 3035);
INSERT INTO Book VALUES (DEFAULT, 'Incidents in the Life of a Slave Girl, Written by Herself', 119, '2004-02-01', '180.txt', 3005);
INSERT INTO Book VALUES (DEFAULT, 'An Essay Concerning Humane Understanding, Volume 1', 68, '2004-01-01', '181.txt', 2986);
INSERT INTO Book VALUES (DEFAULT, 'The Jungle', 120, '2006-03-11', '182.txt', 2986);
INSERT INTO Book VALUES (DEFAULT, 'An Inquiry into the Nature and Causes of the Wealth of Nations', 121, '2002-06-01', '183.txt', 2980);
INSERT INTO Book VALUES (DEFAULT, 'Spenser''s The Faerie Queene, Book I', 122, '2005-03-07', '184.txt', 2969);
INSERT INTO Book VALUES (DEFAULT, 'The Iliad', 33, '2000-06-01', '185.txt', 2955);
INSERT INTO Book VALUES (DEFAULT, 'Bleak House', 20, '1997-08-01', '186.txt', 2943);
INSERT INTO Book VALUES (DEFAULT, 'Andersen''s Fairy Tales', 123, '1999-01-01', '187.txt', 2933);
INSERT INTO Book VALUES (DEFAULT, 'Ghosts', 21, '2005-05-01', '188.txt', 2902);
INSERT INTO Book VALUES (DEFAULT, 'The History of the Peloponnesian War', 124, '2004-12-01', '189.txt', 2895);
INSERT INTO Book VALUES (DEFAULT, 'Tess of the d''Urbervilles: A Pure Woman', 125, '1994-02-01', '190.txt', 2880);
INSERT INTO Book VALUES (DEFAULT, 'Faust [part 1]. Translated Into English in the Original Metres', 98, '2005-01-04', '191.txt', 2861);
INSERT INTO Book VALUES (DEFAULT, 'Cookery and Dining in Imperial Rome', 126, '2009-08-19', '192.txt', 2854);
INSERT INTO Book VALUES (DEFAULT, 'Chaucer''s Works, Volume 4 — The Canterbury Tales (Middle English)', 127, '2007-07-22', '193.txt', 2841);
INSERT INTO Book VALUES (DEFAULT, 'De Profundis', 18, '1997-05-01', '194.txt', 2823);
INSERT INTO Book VALUES (DEFAULT, 'The Duchess of Malfi', 128, '2000-06-01', '195.txt', 2804);
INSERT INTO Book VALUES (DEFAULT, 'At the mountains of madness', 129, '2023-04-27', '196.txt', 2789);
INSERT INTO Book VALUES (DEFAULT, 'Reflections; or Sentences and Moral Maxims', 130, '2005-10-01', '197.txt', 2789);
INSERT INTO Book VALUES (DEFAULT, 'The Marriage of Heaven and Hell', 111, '2014-04-04', '198.txt', 2784);
INSERT INTO Book VALUES (DEFAULT, 'Poirot Investigates', 70, '2020-01-28', '199.txt', 2771);
INSERT INTO Book VALUES (DEFAULT, 'Pascal''s Pensées', 131, '2006-04-27', '200.txt', 2771);
INSERT INTO Book VALUES (DEFAULT, 'Mansfield Park', 14, '1994-06-01', '201.txt', 2769);
INSERT INTO Book VALUES (DEFAULT, 'A Passage to India', 3, '2020-01-22', '202.txt', 2764);
INSERT INTO Book VALUES (DEFAULT, 'Complete Original Short Stories of Guy De Maupassant', 132, '2004-10-02', '203.txt', 2753);
INSERT INTO Book VALUES (DEFAULT, 'The Consolation of Philosophy', 133, '2004-12-11', '204.txt', 2752);
INSERT INTO Book VALUES (DEFAULT, 'The Sun Also Rises', 134, '2022-01-10', '205.txt', 2713);
INSERT INTO Book VALUES (DEFAULT, 'The Possessed (The Devils)', 28, '2005-05-01', '206.txt', 2699);
INSERT INTO Book VALUES (DEFAULT, 'The Innocents Abroad', 31, '2004-06-22', '207.txt', 2684);
INSERT INTO Book VALUES (DEFAULT, 'The Phantom of the Opera', 135, '1994-10-01', '208.txt', 2679);
INSERT INTO Book VALUES (DEFAULT, 'The Wind in the Willows', 136, '1995-07-01', '209.txt', 2675);
INSERT INTO Book VALUES (DEFAULT, 'The Devil''s Dictionary', 137, '1997-07-01', '210.txt', 2673);
INSERT INTO Book VALUES (DEFAULT, 'The Pickwick Papers', 20, '1996-07-01', '211.txt', 2666);
INSERT INTO Book VALUES (DEFAULT, 'Rattle of bones', 138, '2023-04-27', '212.txt', 2658);
INSERT INTO Book VALUES (DEFAULT, 'The Ladies'' Book of Etiquette, and Manual of Politeness', 139, '2011-01-30', '213.txt', 2644);
INSERT INTO Book VALUES (DEFAULT, 'The Antichrist', 41, '2006-09-18', '214.txt', 2641);
INSERT INTO Book VALUES (DEFAULT, 'The Great Controversy Between Christ and Satan', 140, '2008-06-19', '215.txt', 2613);
INSERT INTO Book VALUES (DEFAULT, 'Memoirs of Extraordinary Popular Delusions and the Madness of Crowds', 141, '2008-02-05', '216.txt', 2613);
INSERT INTO Book VALUES (DEFAULT, 'Leaves of Grass', 142, '1998-05-01', '217.txt', 2604);
INSERT INTO Book VALUES (DEFAULT, 'White Nights and Other Stories', 28, '2011-05-05', '218.txt', 2600);
INSERT INTO Book VALUES (DEFAULT, 'Essays by Ralph Waldo Emerson', 143, '2005-09-04', '219.txt', 2599);
INSERT INTO Book VALUES (DEFAULT, 'The History of Herodotus — Volume 1', 144, '2001-07-01', '220.txt', 2581);
INSERT INTO Book VALUES (DEFAULT, 'She Stoops to Conquer; Or, The Mistakes of a Night: A Comedy', 145, '1995-12-01', '221.txt', 2579);
INSERT INTO Book VALUES (DEFAULT, 'Notre-Dame de Paris', 56, '2001-04-01', '222.txt', 2560);
INSERT INTO Book VALUES (DEFAULT, 'Novo dicionário da língua portuguesa (Portuguese)', 146, '2010-03-08', '223.txt', 2520);
INSERT INTO Book VALUES (DEFAULT, 'The Eyes Have It', 147, '2010-03-06', '224.txt', 2518);
INSERT INTO Book VALUES (DEFAULT, 'The Tale of Peter Rabbit', 148, '2005-01-30', '225.txt', 2516);
INSERT INTO Book VALUES (DEFAULT, 'Riders to the Sea', 149, '1997-07-01', '226.txt', 2481);
INSERT INTO Book VALUES (DEFAULT, 'The island of Doctor Moreau', 51, '2004-10-14', '227.txt', 2479);
INSERT INTO Book VALUES (DEFAULT, 'The Decameron of Giovanni Boccaccio', 150, '2007-12-03', '228.txt', 2472);
INSERT INTO Book VALUES (DEFAULT, 'Die Verwandlung (German)', 22, '2007-08-21', '229.txt', 2466);
INSERT INTO Book VALUES (DEFAULT, 'Memoirs of Fanny Hill', 151, '2008-05-02', '230.txt', 2446);
INSERT INTO Book VALUES (DEFAULT, 'Ibong Adarna (Tagalog)', 43, '2005-07-01', '231.txt', 2443);
INSERT INTO Book VALUES (DEFAULT, 'Kidnapped', 23, '2006-01-16', '232.txt', 2442);
INSERT INTO Book VALUES (DEFAULT, 'The Works of Edgar Allan Poe — Volume 1', 76, '2000-04-01', '233.txt', 2433);
INSERT INTO Book VALUES (DEFAULT, 'The Thousand and One Nights, Vol. I.', 43, '2010-11-03', '234.txt', 2433);
INSERT INTO Book VALUES (DEFAULT, 'An Enquiry Concerning Human Understanding', 152, '2006-01-01', '235.txt', 2424);
INSERT INTO Book VALUES (DEFAULT, 'Frankenstein; Or, The Modern Prometheus', 13, '2012-11-23', '236.txt', 2418);
INSERT INTO Book VALUES (DEFAULT, 'Best Russian Short Stories', 43, '2004-09-11', '237.txt', 2417);
INSERT INTO Book VALUES (DEFAULT, 'A Journey to the Centre of the Earth', 81, '2006-07-18', '238.txt', 2407);
INSERT INTO Book VALUES (DEFAULT, 'The Murder on the Links', 70, '2019-02-11', '239.txt', 2389);
INSERT INTO Book VALUES (DEFAULT, 'The Red Badge of Courage: An Episode of the American Civil War', 153, '1993-07-01', '240.txt', 2387);
INSERT INTO Book VALUES (DEFAULT, 'Democracy in America — Volume 1', 154, '2006-01-21', '241.txt', 2387);
INSERT INTO Book VALUES (DEFAULT, 'The Rape of the Lock, and Other Poems', 155, '2006-01-01', '242.txt', 2384);
INSERT INTO Book VALUES (DEFAULT, 'The Rubaiyat of Omar Khayyam', 156, '1995-04-01', '243.txt', 2383);
INSERT INTO Book VALUES (DEFAULT, 'A Complete Dictionary of Synonyms and Antonyms', 157, '2016-02-08', '244.txt', 2382);
INSERT INTO Book VALUES (DEFAULT, 'The Forsyte Saga, Volume I.', 158, '2006-06-14', '245.txt', 2377);
INSERT INTO Book VALUES (DEFAULT, 'The Aeneid', 159, '1995-03-01', '246.txt', 2371);
INSERT INTO Book VALUES (DEFAULT, 'A fighting man of Mars', 160, '2023-05-03', '247.txt', 2366);
INSERT INTO Book VALUES (DEFAULT, 'The Adventures of Pinocchio', 161, '2006-01-12', '248.txt', 2338);
INSERT INTO Book_Categories VALUES (1, 1);
INSERT INTO Book_Categories VALUES (1, 2);
INSERT INTO Book_Categories VALUES (2, 3);
INSERT INTO Book_Categories VALUES (2, 4);
INSERT INTO Book_Categories VALUES (3, 5);
INSERT INTO Book_Categories VALUES (3, 4);
INSERT INTO Book_Categories VALUES (3, 6);
INSERT INTO Book_Categories VALUES (4, 7);
INSERT INTO Book_Categories VALUES (4, 4);
INSERT INTO Book_Categories VALUES (5, 8);
INSERT INTO Book_Categories VALUES (5, 4);
INSERT INTO Book_Categories VALUES (5, 9);
INSERT INTO Book_Categories VALUES (6, 10);
INSERT INTO Book_Categories VALUES (6, 11);
INSERT INTO Book_Categories VALUES (7, 12);
INSERT INTO Book_Categories VALUES (7, 4);
INSERT INTO Book_Categories VALUES (7, 6);
INSERT INTO Book_Categories VALUES (8, 13);
INSERT INTO Book_Categories VALUES (8, 4);
INSERT INTO Book_Categories VALUES (8, 14);
INSERT INTO Book_Categories VALUES (8, 15);
INSERT INTO Book_Categories VALUES (9, 16);
INSERT INTO Book_Categories VALUES (9, 4);
INSERT INTO Book_Categories VALUES (10, 17);
INSERT INTO Book_Categories VALUES (11, 18);
INSERT INTO Book_Categories VALUES (11, 4);
INSERT INTO Book_Categories VALUES (12, 5);
INSERT INTO Book_Categories VALUES (12, 4);
INSERT INTO Book_Categories VALUES (13, 19);
INSERT INTO Book_Categories VALUES (13, 4);
INSERT INTO Book_Categories VALUES (13, 16);
INSERT INTO Book_Categories VALUES (14, 20);
INSERT INTO Book_Categories VALUES (14, 14);
INSERT INTO Book_Categories VALUES (14, 21);
INSERT INTO Book_Categories VALUES (14, 4);
INSERT INTO Book_Categories VALUES (15, 22);
INSERT INTO Book_Categories VALUES (15, 23);
INSERT INTO Book_Categories VALUES (15, 24);
INSERT INTO Book_Categories VALUES (16, 25);
INSERT INTO Book_Categories VALUES (16, 4);
INSERT INTO Book_Categories VALUES (17, 16);
INSERT INTO Book_Categories VALUES (17, 4);
INSERT INTO Book_Categories VALUES (18, 26);
INSERT INTO Book_Categories VALUES (18, 14);
INSERT INTO Book_Categories VALUES (18, 27);
INSERT INTO Book_Categories VALUES (18, 4);
INSERT INTO Book_Categories VALUES (19, 28);
INSERT INTO Book_Categories VALUES (19, 29);
INSERT INTO Book_Categories VALUES (20, 30);
INSERT INTO Book_Categories VALUES (20, 31);
INSERT INTO Book_Categories VALUES (20, 4);
INSERT INTO Book_Categories VALUES (20, 14);
INSERT INTO Book_Categories VALUES (20, 32);
INSERT INTO Book_Categories VALUES (21, 33);
INSERT INTO Book_Categories VALUES (21, 4);
INSERT INTO Book_Categories VALUES (22, 34);
INSERT INTO Book_Categories VALUES (22, 2);
INSERT INTO Book_Categories VALUES (23, 7);
INSERT INTO Book_Categories VALUES (23, 4);
INSERT INTO Book_Categories VALUES (23, 14);
INSERT INTO Book_Categories VALUES (23, 35);
INSERT INTO Book_Categories VALUES (23, 36);
INSERT INTO Book_Categories VALUES (24, 37);
INSERT INTO Book_Categories VALUES (24, 4);
INSERT INTO Book_Categories VALUES (25, 26);
INSERT INTO Book_Categories VALUES (25, 14);
INSERT INTO Book_Categories VALUES (25, 38);
INSERT INTO Book_Categories VALUES (25, 4);
INSERT INTO Book_Categories VALUES (25, 39);
INSERT INTO Book_Categories VALUES (25, 16);
INSERT INTO Book_Categories VALUES (25, 40);
INSERT INTO Book_Categories VALUES (25, 20);
INSERT INTO Book_Categories VALUES (25, 41);
INSERT INTO Book_Categories VALUES (25, 42);
INSERT INTO Book_Categories VALUES (26, 43);
INSERT INTO Book_Categories VALUES (26, 2);
INSERT INTO Book_Categories VALUES (26, 44);
INSERT INTO Book_Categories VALUES (27, 33);
INSERT INTO Book_Categories VALUES (27, 4);
INSERT INTO Book_Categories VALUES (28, 25);
INSERT INTO Book_Categories VALUES (28, 4);
INSERT INTO Book_Categories VALUES (29, 45);
INSERT INTO Book_Categories VALUES (29, 4);
INSERT INTO Book_Categories VALUES (30, 33);
INSERT INTO Book_Categories VALUES (30, 4);
INSERT INTO Book_Categories VALUES (30, 46);
INSERT INTO Book_Categories VALUES (31, 47);
INSERT INTO Book_Categories VALUES (31, 48);
INSERT INTO Book_Categories VALUES (31, 39);
INSERT INTO Book_Categories VALUES (31, 49);
INSERT INTO Book_Categories VALUES (32, 26);
INSERT INTO Book_Categories VALUES (32, 50);
INSERT INTO Book_Categories VALUES (32, 51);
INSERT INTO Book_Categories VALUES (32, 4);
INSERT INTO Book_Categories VALUES (32, 14);
INSERT INTO Book_Categories VALUES (32, 52);
INSERT INTO Book_Categories VALUES (33, 53);
INSERT INTO Book_Categories VALUES (33, 4);
INSERT INTO Book_Categories VALUES (33, 16);
INSERT INTO Book_Categories VALUES (34, 54);
INSERT INTO Book_Categories VALUES (34, 44);
INSERT INTO Book_Categories VALUES (34, 31);
INSERT INTO Book_Categories VALUES (34, 4);
INSERT INTO Book_Categories VALUES (34, 14);
INSERT INTO Book_Categories VALUES (35, 7);
INSERT INTO Book_Categories VALUES (35, 4);
INSERT INTO Book_Categories VALUES (35, 55);
INSERT INTO Book_Categories VALUES (35, 56);
INSERT INTO Book_Categories VALUES (36, 26);
INSERT INTO Book_Categories VALUES (36, 4);
INSERT INTO Book_Categories VALUES (36, 14);
INSERT INTO Book_Categories VALUES (36, 57);
INSERT INTO Book_Categories VALUES (37, 58);
INSERT INTO Book_Categories VALUES (37, 4);
INSERT INTO Book_Categories VALUES (37, 14);
INSERT INTO Book_Categories VALUES (37, 59);
INSERT INTO Book_Categories VALUES (38, 60);
INSERT INTO Book_Categories VALUES (38, 16);
INSERT INTO Book_Categories VALUES (38, 40);
INSERT INTO Book_Categories VALUES (38, 61);
INSERT INTO Book_Categories VALUES (38, 62);
INSERT INTO Book_Categories VALUES (38, 63);
INSERT INTO Book_Categories VALUES (38, 64);
INSERT INTO Book_Categories VALUES (38, 65);
INSERT INTO Book_Categories VALUES (39, 5);
INSERT INTO Book_Categories VALUES (39, 4);
INSERT INTO Book_Categories VALUES (40, 66);
INSERT INTO Book_Categories VALUES (40, 4);
INSERT INTO Book_Categories VALUES (41, 67);
INSERT INTO Book_Categories VALUES (41, 4);
INSERT INTO Book_Categories VALUES (41, 68);
INSERT INTO Book_Categories VALUES (42, 69);
INSERT INTO Book_Categories VALUES (42, 44);
INSERT INTO Book_Categories VALUES (42, 70);
INSERT INTO Book_Categories VALUES (43, 71);
INSERT INTO Book_Categories VALUES (44, 45);
INSERT INTO Book_Categories VALUES (44, 4);
INSERT INTO Book_Categories VALUES (45, 72);
INSERT INTO Book_Categories VALUES (45, 23);
INSERT INTO Book_Categories VALUES (46, 31);
INSERT INTO Book_Categories VALUES (47, 73);
INSERT INTO Book_Categories VALUES (47, 74);
INSERT INTO Book_Categories VALUES (47, 75);
INSERT INTO Book_Categories VALUES (48, 76);
INSERT INTO Book_Categories VALUES (49, 77);
INSERT INTO Book_Categories VALUES (49, 44);
INSERT INTO Book_Categories VALUES (50, 78);
INSERT INTO Book_Categories VALUES (50, 55);
INSERT INTO Book_Categories VALUES (50, 79);
INSERT INTO Book_Categories VALUES (50, 4);
INSERT INTO Book_Categories VALUES (51, 19);
INSERT INTO Book_Categories VALUES (51, 4);
INSERT INTO Book_Categories VALUES (52, 5);
INSERT INTO Book_Categories VALUES (52, 4);
INSERT INTO Book_Categories VALUES (53, 80);
INSERT INTO Book_Categories VALUES (53, 4);
INSERT INTO Book_Categories VALUES (54, 81);
INSERT INTO Book_Categories VALUES (54, 29);
INSERT INTO Book_Categories VALUES (55, 82);
INSERT INTO Book_Categories VALUES (56, 83);
INSERT INTO Book_Categories VALUES (57, 84);
INSERT INTO Book_Categories VALUES (57, 4);
INSERT INTO Book_Categories VALUES (58, 85);
INSERT INTO Book_Categories VALUES (59, 45);
INSERT INTO Book_Categories VALUES (59, 4);
INSERT INTO Book_Categories VALUES (59, 86);
INSERT INTO Book_Categories VALUES (59, 14);
INSERT INTO Book_Categories VALUES (59, 87);
INSERT INTO Book_Categories VALUES (59, 88);
INSERT INTO Book_Categories VALUES (60, 89);
INSERT INTO Book_Categories VALUES (60, 4);
INSERT INTO Book_Categories VALUES (61, 90);
INSERT INTO Book_Categories VALUES (61, 2);
INSERT INTO Book_Categories VALUES (62, 91);
INSERT INTO Book_Categories VALUES (62, 70);
INSERT INTO Book_Categories VALUES (63, 92);
INSERT INTO Book_Categories VALUES (63, 4);
INSERT INTO Book_Categories VALUES (64, 93);
INSERT INTO Book_Categories VALUES (64, 4);
INSERT INTO Book_Categories VALUES (65, 94);
INSERT INTO Book_Categories VALUES (65, 57);
INSERT INTO Book_Categories VALUES (65, 24);
INSERT INTO Book_Categories VALUES (65, 95);
INSERT INTO Book_Categories VALUES (65, 96);
INSERT INTO Book_Categories VALUES (65, 97);
INSERT INTO Book_Categories VALUES (65, 55);
INSERT INTO Book_Categories VALUES (66, 53);
INSERT INTO Book_Categories VALUES (66, 4);
INSERT INTO Book_Categories VALUES (66, 16);
INSERT INTO Book_Categories VALUES (67, 98);
INSERT INTO Book_Categories VALUES (67, 44);
INSERT INTO Book_Categories VALUES (67, 99);
INSERT INTO Book_Categories VALUES (68, 25);
INSERT INTO Book_Categories VALUES (68, 4);
INSERT INTO Book_Categories VALUES (69, 69);
INSERT INTO Book_Categories VALUES (69, 74);
INSERT INTO Book_Categories VALUES (70, 100);
INSERT INTO Book_Categories VALUES (70, 101);
INSERT INTO Book_Categories VALUES (71, 102);
INSERT INTO Book_Categories VALUES (72, 103);
INSERT INTO Book_Categories VALUES (72, 4);
INSERT INTO Book_Categories VALUES (73, 104);
INSERT INTO Book_Categories VALUES (73, 29);
INSERT INTO Book_Categories VALUES (74, 58);
INSERT INTO Book_Categories VALUES (74, 4);
INSERT INTO Book_Categories VALUES (75, 53);
INSERT INTO Book_Categories VALUES (75, 4);
INSERT INTO Book_Categories VALUES (75, 16);
INSERT INTO Book_Categories VALUES (76, 5);
INSERT INTO Book_Categories VALUES (76, 4);
INSERT INTO Book_Categories VALUES (77, 8);
INSERT INTO Book_Categories VALUES (77, 4);
INSERT INTO Book_Categories VALUES (77, 9);
INSERT INTO Book_Categories VALUES (78, 105);
INSERT INTO Book_Categories VALUES (78, 4);
INSERT INTO Book_Categories VALUES (78, 55);
INSERT INTO Book_Categories VALUES (78, 106);
INSERT INTO Book_Categories VALUES (79, 25);
INSERT INTO Book_Categories VALUES (79, 4);
INSERT INTO Book_Categories VALUES (80, 26);
INSERT INTO Book_Categories VALUES (80, 4);
INSERT INTO Book_Categories VALUES (81, 45);
INSERT INTO Book_Categories VALUES (81, 4);
INSERT INTO Book_Categories VALUES (82, 16);
INSERT INTO Book_Categories VALUES (82, 55);
INSERT INTO Book_Categories VALUES (82, 57);
INSERT INTO Book_Categories VALUES (82, 4);
INSERT INTO Book_Categories VALUES (83, 103);
INSERT INTO Book_Categories VALUES (83, 4);
INSERT INTO Book_Categories VALUES (83, 14);
INSERT INTO Book_Categories VALUES (83, 57);
INSERT INTO Book_Categories VALUES (84, 107);
INSERT INTO Book_Categories VALUES (84, 74);
INSERT INTO Book_Categories VALUES (85, 23);
INSERT INTO Book_Categories VALUES (85, 2);
INSERT INTO Book_Categories VALUES (86, 108);
INSERT INTO Book_Categories VALUES (86, 14);
INSERT INTO Book_Categories VALUES (86, 109);
INSERT INTO Book_Categories VALUES (86, 4);
INSERT INTO Book_Categories VALUES (86, 110);
INSERT INTO Book_Categories VALUES (87, 34);
INSERT INTO Book_Categories VALUES (87, 2);
INSERT INTO Book_Categories VALUES (88, 111);
INSERT INTO Book_Categories VALUES (88, 112);
INSERT INTO Book_Categories VALUES (88, 16);
INSERT INTO Book_Categories VALUES (88, 113);
INSERT INTO Book_Categories VALUES (88, 4);
INSERT INTO Book_Categories VALUES (89, 114);
INSERT INTO Book_Categories VALUES (89, 115);
INSERT INTO Book_Categories VALUES (89, 44);
INSERT INTO Book_Categories VALUES (89, 70);
INSERT INTO Book_Categories VALUES (90, 116);
INSERT INTO Book_Categories VALUES (90, 117);
INSERT INTO Book_Categories VALUES (91, 118);
INSERT INTO Book_Categories VALUES (91, 4);
INSERT INTO Book_Categories VALUES (92, 119);
INSERT INTO Book_Categories VALUES (92, 120);
INSERT INTO Book_Categories VALUES (92, 121);
INSERT INTO Book_Categories VALUES (92, 24);
INSERT INTO Book_Categories VALUES (92, 122);
INSERT INTO Book_Categories VALUES (93, 123);
INSERT INTO Book_Categories VALUES (94, 45);
INSERT INTO Book_Categories VALUES (94, 4);
INSERT INTO Book_Categories VALUES (95, 124);
INSERT INTO Book_Categories VALUES (95, 55);
INSERT INTO Book_Categories VALUES (95, 57);
INSERT INTO Book_Categories VALUES (95, 4);
INSERT INTO Book_Categories VALUES (96, 125);
INSERT INTO Book_Categories VALUES (96, 24);
INSERT INTO Book_Categories VALUES (97, 107);
INSERT INTO Book_Categories VALUES (97, 74);
INSERT INTO Book_Categories VALUES (98, 126);
INSERT INTO Book_Categories VALUES (98, 44);
INSERT INTO Book_Categories VALUES (99, 127);
INSERT INTO Book_Categories VALUES (99, 16);
INSERT INTO Book_Categories VALUES (99, 4);
INSERT INTO Book_Categories VALUES (99, 128);
INSERT INTO Book_Categories VALUES (100, 129);
INSERT INTO Book_Categories VALUES (100, 4);
INSERT INTO Book_Categories VALUES (101, 130);
INSERT INTO Book_Categories VALUES (101, 74);
INSERT INTO Book_Categories VALUES (102, 131);
INSERT INTO Book_Categories VALUES (102, 4);
INSERT INTO Book_Categories VALUES (103, 26);
INSERT INTO Book_Categories VALUES (103, 14);
INSERT INTO Book_Categories VALUES (103, 27);
INSERT INTO Book_Categories VALUES (103, 4);
INSERT INTO Book_Categories VALUES (104, 132);
INSERT INTO Book_Categories VALUES (104, 4);
INSERT INTO Book_Categories VALUES (105, 16);
INSERT INTO Book_Categories VALUES (105, 55);
INSERT INTO Book_Categories VALUES (105, 57);
INSERT INTO Book_Categories VALUES (105, 4);
INSERT INTO Book_Categories VALUES (106, 133);
INSERT INTO Book_Categories VALUES (106, 4);
INSERT INTO Book_Categories VALUES (106, 14);
INSERT INTO Book_Categories VALUES (106, 134);
INSERT INTO Book_Categories VALUES (107, 103);
INSERT INTO Book_Categories VALUES (107, 57);
INSERT INTO Book_Categories VALUES (108, 34);
INSERT INTO Book_Categories VALUES (108, 2);
INSERT INTO Book_Categories VALUES (109, 135);
INSERT INTO Book_Categories VALUES (110, 28);
INSERT INTO Book_Categories VALUES (110, 29);
INSERT INTO Book_Categories VALUES (111, 136);
INSERT INTO Book_Categories VALUES (111, 70);
INSERT INTO Book_Categories VALUES (112, 45);
INSERT INTO Book_Categories VALUES (112, 29);
INSERT INTO Book_Categories VALUES (113, 72);
INSERT INTO Book_Categories VALUES (114, 28);
INSERT INTO Book_Categories VALUES (114, 4);
INSERT INTO Book_Categories VALUES (114, 74);
INSERT INTO Book_Categories VALUES (115, 137);
INSERT INTO Book_Categories VALUES (116, 8);
INSERT INTO Book_Categories VALUES (116, 4);
INSERT INTO Book_Categories VALUES (117, 25);
INSERT INTO Book_Categories VALUES (117, 4);
INSERT INTO Book_Categories VALUES (117, 46);
INSERT INTO Book_Categories VALUES (118, 25);
INSERT INTO Book_Categories VALUES (118, 4);
INSERT INTO Book_Categories VALUES (119, 138);
INSERT INTO Book_Categories VALUES (119, 139);
INSERT INTO Book_Categories VALUES (120, 26);
INSERT INTO Book_Categories VALUES (120, 4);
INSERT INTO Book_Categories VALUES (121, 140);
INSERT INTO Book_Categories VALUES (121, 24);
INSERT INTO Book_Categories VALUES (121, 141);
INSERT INTO Book_Categories VALUES (122, 142);
INSERT INTO Book_Categories VALUES (122, 74);
INSERT INTO Book_Categories VALUES (123, 143);
INSERT INTO Book_Categories VALUES (123, 70);
INSERT INTO Book_Categories VALUES (123, 144);
INSERT INTO Book_Categories VALUES (124, 115);
INSERT INTO Book_Categories VALUES (124, 145);
INSERT INTO Book_Categories VALUES (125, 60);
INSERT INTO Book_Categories VALUES (125, 146);
INSERT INTO Book_Categories VALUES (125, 147);
INSERT INTO Book_Categories VALUES (126, 148);
INSERT INTO Book_Categories VALUES (126, 2);
INSERT INTO Book_Categories VALUES (126, 149);
INSERT INTO Book_Categories VALUES (127, 127);
INSERT INTO Book_Categories VALUES (127, 16);
INSERT INTO Book_Categories VALUES (127, 4);
INSERT INTO Book_Categories VALUES (128, 150);
INSERT INTO Book_Categories VALUES (128, 151);
INSERT INTO Book_Categories VALUES (129, 152);
INSERT INTO Book_Categories VALUES (129, 74);
INSERT INTO Book_Categories VALUES (129, 55);
INSERT INTO Book_Categories VALUES (130, 153);
INSERT INTO Book_Categories VALUES (130, 70);
INSERT INTO Book_Categories VALUES (131, 154);
INSERT INTO Book_Categories VALUES (131, 4);
INSERT INTO Book_Categories VALUES (132, 155);
INSERT INTO Book_Categories VALUES (132, 141);
INSERT INTO Book_Categories VALUES (132, 24);
INSERT INTO Book_Categories VALUES (133, 148);
INSERT INTO Book_Categories VALUES (133, 2);
INSERT INTO Book_Categories VALUES (133, 156);
INSERT INTO Book_Categories VALUES (133, 157);
INSERT INTO Book_Categories VALUES (134, 116);
INSERT INTO Book_Categories VALUES (135, 158);
INSERT INTO Book_Categories VALUES (135, 159);
INSERT INTO Book_Categories VALUES (136, 82);
INSERT INTO Book_Categories VALUES (137, 160);
INSERT INTO Book_Categories VALUES (138, 161);
INSERT INTO Book_Categories VALUES (138, 142);
INSERT INTO Book_Categories VALUES (138, 29);
INSERT INTO Book_Categories VALUES (138, 4);
INSERT INTO Book_Categories VALUES (138, 44);
INSERT INTO Book_Categories VALUES (139, 162);
INSERT INTO Book_Categories VALUES (140, 23);
INSERT INTO Book_Categories VALUES (140, 55);
INSERT INTO Book_Categories VALUES (140, 4);
INSERT INTO Book_Categories VALUES (141, 163);
INSERT INTO Book_Categories VALUES (141, 14);
INSERT INTO Book_Categories VALUES (141, 164);
INSERT INTO Book_Categories VALUES (141, 165);
INSERT INTO Book_Categories VALUES (142, 166);
INSERT INTO Book_Categories VALUES (143, 16);
INSERT INTO Book_Categories VALUES (143, 4);
INSERT INTO Book_Categories VALUES (144, 167);
INSERT INTO Book_Categories VALUES (145, 168);
INSERT INTO Book_Categories VALUES (145, 141);
INSERT INTO Book_Categories VALUES (145, 24);
INSERT INTO Book_Categories VALUES (145, 169);
INSERT INTO Book_Categories VALUES (146, 58);
INSERT INTO Book_Categories VALUES (146, 4);
INSERT INTO Book_Categories VALUES (146, 170);
INSERT INTO Book_Categories VALUES (146, 171);
INSERT INTO Book_Categories VALUES (146, 172);
INSERT INTO Book_Categories VALUES (146, 55);
INSERT INTO Book_Categories VALUES (147, 16);
INSERT INTO Book_Categories VALUES (147, 4);
INSERT INTO Book_Categories VALUES (148, 173);
INSERT INTO Book_Categories VALUES (149, 148);
INSERT INTO Book_Categories VALUES (149, 2);
INSERT INTO Book_Categories VALUES (149, 156);
INSERT INTO Book_Categories VALUES (149, 157);
INSERT INTO Book_Categories VALUES (150, 25);
INSERT INTO Book_Categories VALUES (150, 4);
INSERT INTO Book_Categories VALUES (151, 174);
INSERT INTO Book_Categories VALUES (151, 4);
INSERT INTO Book_Categories VALUES (152, 175);
INSERT INTO Book_Categories VALUES (152, 176);
INSERT INTO Book_Categories VALUES (152, 75);
INSERT INTO Book_Categories VALUES (153, 177);
INSERT INTO Book_Categories VALUES (153, 70);
INSERT INTO Book_Categories VALUES (153, 178);
INSERT INTO Book_Categories VALUES (154, 26);
INSERT INTO Book_Categories VALUES (154, 172);
INSERT INTO Book_Categories VALUES (154, 109);
INSERT INTO Book_Categories VALUES (154, 4);
INSERT INTO Book_Categories VALUES (155, 179);
INSERT INTO Book_Categories VALUES (156, 26);
INSERT INTO Book_Categories VALUES (156, 14);
INSERT INTO Book_Categories VALUES (156, 180);
INSERT INTO Book_Categories VALUES (156, 4);
INSERT INTO Book_Categories VALUES (157, 25);
INSERT INTO Book_Categories VALUES (158, 53);
INSERT INTO Book_Categories VALUES (158, 4);
INSERT INTO Book_Categories VALUES (158, 16);
INSERT INTO Book_Categories VALUES (159, 16);
INSERT INTO Book_Categories VALUES (159, 55);
INSERT INTO Book_Categories VALUES (159, 57);
INSERT INTO Book_Categories VALUES (159, 4);
INSERT INTO Book_Categories VALUES (159, 181);
INSERT INTO Book_Categories VALUES (159, 182);
INSERT INTO Book_Categories VALUES (160, 51);
INSERT INTO Book_Categories VALUES (160, 55);
INSERT INTO Book_Categories VALUES (160, 2);
INSERT INTO Book_Categories VALUES (160, 44);
INSERT INTO Book_Categories VALUES (160, 57);
INSERT INTO Book_Categories VALUES (161, 69);
INSERT INTO Book_Categories VALUES (161, 74);
INSERT INTO Book_Categories VALUES (162, 183);
INSERT INTO Book_Categories VALUES (163, 184);
INSERT INTO Book_Categories VALUES (163, 4);
INSERT INTO Book_Categories VALUES (164, 185);
INSERT INTO Book_Categories VALUES (164, 62);
INSERT INTO Book_Categories VALUES (164, 101);
INSERT INTO Book_Categories VALUES (165, 78);
INSERT INTO Book_Categories VALUES (165, 55);
INSERT INTO Book_Categories VALUES (165, 79);
INSERT INTO Book_Categories VALUES (165, 4);
INSERT INTO Book_Categories VALUES (166, 103);
INSERT INTO Book_Categories VALUES (166, 4);
INSERT INTO Book_Categories VALUES (167, 186);
INSERT INTO Book_Categories VALUES (167, 70);
INSERT INTO Book_Categories VALUES (167, 44);
INSERT INTO Book_Categories VALUES (167, 99);
INSERT INTO Book_Categories VALUES (168, 187);
INSERT INTO Book_Categories VALUES (168, 39);
INSERT INTO Book_Categories VALUES (169, 188);
INSERT INTO Book_Categories VALUES (170, 82);
INSERT INTO Book_Categories VALUES (171, 58);
INSERT INTO Book_Categories VALUES (171, 4);
INSERT INTO Book_Categories VALUES (172, 82);
INSERT INTO Book_Categories VALUES (173, 189);
INSERT INTO Book_Categories VALUES (173, 2);
INSERT INTO Book_Categories VALUES (173, 190);
INSERT INTO Book_Categories VALUES (173, 14);
INSERT INTO Book_Categories VALUES (174, 34);
INSERT INTO Book_Categories VALUES (174, 2);
INSERT INTO Book_Categories VALUES (175, 191);
INSERT INTO Book_Categories VALUES (176, 192);
INSERT INTO Book_Categories VALUES (176, 44);
INSERT INTO Book_Categories VALUES (177, 141);
INSERT INTO Book_Categories VALUES (177, 48);
INSERT INTO Book_Categories VALUES (177, 193);
INSERT INTO Book_Categories VALUES (177, 74);
INSERT INTO Book_Categories VALUES (178, 194);
INSERT INTO Book_Categories VALUES (178, 4);
INSERT INTO Book_Categories VALUES (179, 25);
INSERT INTO Book_Categories VALUES (179, 4);
INSERT INTO Book_Categories VALUES (180, 195);
INSERT INTO Book_Categories VALUES (180, 141);
INSERT INTO Book_Categories VALUES (180, 24);
INSERT INTO Book_Categories VALUES (180, 172);
INSERT INTO Book_Categories VALUES (181, 116);
INSERT INTO Book_Categories VALUES (181, 74);
INSERT INTO Book_Categories VALUES (182, 196);
INSERT INTO Book_Categories VALUES (182, 4);
INSERT INTO Book_Categories VALUES (183, 197);
INSERT INTO Book_Categories VALUES (184, 177);
INSERT INTO Book_Categories VALUES (184, 198);
INSERT INTO Book_Categories VALUES (184, 70);
INSERT INTO Book_Categories VALUES (185, 69);
INSERT INTO Book_Categories VALUES (185, 44);
INSERT INTO Book_Categories VALUES (186, 199);
INSERT INTO Book_Categories VALUES (186, 4);
INSERT INTO Book_Categories VALUES (187, 72);
INSERT INTO Book_Categories VALUES (187, 200);
INSERT INTO Book_Categories VALUES (187, 44);
INSERT INTO Book_Categories VALUES (188, 201);
INSERT INTO Book_Categories VALUES (188, 2);
INSERT INTO Book_Categories VALUES (188, 172);
INSERT INTO Book_Categories VALUES (188, 57);
INSERT INTO Book_Categories VALUES (188, 44);
INSERT INTO Book_Categories VALUES (189, 202);
INSERT INTO Book_Categories VALUES (189, 14);
INSERT INTO Book_Categories VALUES (189, 203);
INSERT INTO Book_Categories VALUES (190, 7);
INSERT INTO Book_Categories VALUES (190, 4);
INSERT INTO Book_Categories VALUES (191, 204);
INSERT INTO Book_Categories VALUES (191, 44);
INSERT INTO Book_Categories VALUES (191, 23);
INSERT INTO Book_Categories VALUES (191, 2);
INSERT INTO Book_Categories VALUES (192, 205);
INSERT INTO Book_Categories VALUES (192, 74);
INSERT INTO Book_Categories VALUES (193, 206);
INSERT INTO Book_Categories VALUES (193, 70);
INSERT INTO Book_Categories VALUES (194, 207);
INSERT INTO Book_Categories VALUES (195, 148);
INSERT INTO Book_Categories VALUES (195, 190);
INSERT INTO Book_Categories VALUES (195, 2);
INSERT INTO Book_Categories VALUES (196, 28);
INSERT INTO Book_Categories VALUES (196, 4);
INSERT INTO Book_Categories VALUES (196, 208);
INSERT INTO Book_Categories VALUES (197, 209);
INSERT INTO Book_Categories VALUES (198, 91);
INSERT INTO Book_Categories VALUES (199, 127);
INSERT INTO Book_Categories VALUES (199, 16);
INSERT INTO Book_Categories VALUES (199, 4);
INSERT INTO Book_Categories VALUES (200, 210);
INSERT INTO Book_Categories VALUES (201, 16);
INSERT INTO Book_Categories VALUES (201, 4);
INSERT INTO Book_Categories VALUES (202, 108);
INSERT INTO Book_Categories VALUES (202, 115);
INSERT INTO Book_Categories VALUES (202, 4);
INSERT INTO Book_Categories VALUES (202, 172);
INSERT INTO Book_Categories VALUES (202, 87);
INSERT INTO Book_Categories VALUES (203, 211);
INSERT INTO Book_Categories VALUES (203, 44);
INSERT INTO Book_Categories VALUES (204, 212);
INSERT INTO Book_Categories VALUES (205, 213);
INSERT INTO Book_Categories VALUES (205, 20);
INSERT INTO Book_Categories VALUES (205, 4);
INSERT INTO Book_Categories VALUES (205, 78);
INSERT INTO Book_Categories VALUES (205, 14);
INSERT INTO Book_Categories VALUES (205, 214);
INSERT INTO Book_Categories VALUES (206, 108);
INSERT INTO Book_Categories VALUES (206, 55);
INSERT INTO Book_Categories VALUES (206, 56);
INSERT INTO Book_Categories VALUES (206, 4);
INSERT INTO Book_Categories VALUES (206, 51);
INSERT INTO Book_Categories VALUES (207, 215);
INSERT INTO Book_Categories VALUES (207, 216);
INSERT INTO Book_Categories VALUES (208, 37);
INSERT INTO Book_Categories VALUES (208, 4);
INSERT INTO Book_Categories VALUES (208, 44);
INSERT INTO Book_Categories VALUES (209, 28);
INSERT INTO Book_Categories VALUES (209, 4);
INSERT INTO Book_Categories VALUES (210, 60);
INSERT INTO Book_Categories VALUES (210, 62);
INSERT INTO Book_Categories VALUES (210, 49);
INSERT INTO Book_Categories VALUES (210, 217);
INSERT INTO Book_Categories VALUES (211, 5);
INSERT INTO Book_Categories VALUES (211, 4);
INSERT INTO Book_Categories VALUES (211, 218);
INSERT INTO Book_Categories VALUES (212, 103);
INSERT INTO Book_Categories VALUES (212, 4);
INSERT INTO Book_Categories VALUES (213, 219);
INSERT INTO Book_Categories VALUES (213, 141);
INSERT INTO Book_Categories VALUES (213, 220);
INSERT INTO Book_Categories VALUES (214, 221);
INSERT INTO Book_Categories VALUES (214, 222);
INSERT INTO Book_Categories VALUES (215, 223);
INSERT INTO Book_Categories VALUES (215, 224);
INSERT INTO Book_Categories VALUES (216, 225);
INSERT INTO Book_Categories VALUES (216, 226);
INSERT INTO Book_Categories VALUES (216, 68);
INSERT INTO Book_Categories VALUES (217, 227);
INSERT INTO Book_Categories VALUES (217, 57);
INSERT INTO Book_Categories VALUES (218, 228);
INSERT INTO Book_Categories VALUES (218, 44);
INSERT INTO Book_Categories VALUES (219, 229);
INSERT INTO Book_Categories VALUES (220, 230);
INSERT INTO Book_Categories VALUES (220, 14);
INSERT INTO Book_Categories VALUES (220, 231);
INSERT INTO Book_Categories VALUES (221, 34);
INSERT INTO Book_Categories VALUES (222, 26);
INSERT INTO Book_Categories VALUES (222, 4);
INSERT INTO Book_Categories VALUES (222, 14);
INSERT INTO Book_Categories VALUES (222, 232);
INSERT INTO Book_Categories VALUES (222, 233);
INSERT INTO Book_Categories VALUES (223, 234);
INSERT INTO Book_Categories VALUES (223, 62);
INSERT INTO Book_Categories VALUES (224, 25);
INSERT INTO Book_Categories VALUES (225, 235);
INSERT INTO Book_Categories VALUES (225, 29);
INSERT INTO Book_Categories VALUES (226, 236);
INSERT INTO Book_Categories VALUES (226, 2);
INSERT INTO Book_Categories VALUES (227, 25);
INSERT INTO Book_Categories VALUES (227, 4);
INSERT INTO Book_Categories VALUES (227, 82);
INSERT INTO Book_Categories VALUES (228, 237);
INSERT INTO Book_Categories VALUES (228, 178);
INSERT INTO Book_Categories VALUES (228, 14);
INSERT INTO Book_Categories VALUES (228, 4);
INSERT INTO Book_Categories VALUES (229, 33);
INSERT INTO Book_Categories VALUES (229, 4);
INSERT INTO Book_Categories VALUES (230, 16);
INSERT INTO Book_Categories VALUES (230, 4);
INSERT INTO Book_Categories VALUES (231, 114);
INSERT INTO Book_Categories VALUES (231, 31);
INSERT INTO Book_Categories VALUES (232, 26);
INSERT INTO Book_Categories VALUES (232, 14);
INSERT INTO Book_Categories VALUES (232, 39);
INSERT INTO Book_Categories VALUES (232, 4);
INSERT INTO Book_Categories VALUES (233, 28);
INSERT INTO Book_Categories VALUES (233, 57);
INSERT INTO Book_Categories VALUES (234, 72);
INSERT INTO Book_Categories VALUES (234, 238);
INSERT INTO Book_Categories VALUES (235, 82);
INSERT INTO Book_Categories VALUES (236, 25);
INSERT INTO Book_Categories VALUES (236, 4);
INSERT INTO Book_Categories VALUES (237, 239);
INSERT INTO Book_Categories VALUES (237, 44);
INSERT INTO Book_Categories VALUES (238, 25);
INSERT INTO Book_Categories VALUES (238, 240);
INSERT INTO Book_Categories VALUES (238, 4);
INSERT INTO Book_Categories VALUES (239, 127);
INSERT INTO Book_Categories VALUES (239, 16);
INSERT INTO Book_Categories VALUES (239, 4);
INSERT INTO Book_Categories VALUES (240, 26);
INSERT INTO Book_Categories VALUES (240, 14);
INSERT INTO Book_Categories VALUES (240, 241);
INSERT INTO Book_Categories VALUES (240, 4);
INSERT INTO Book_Categories VALUES (241, 141);
INSERT INTO Book_Categories VALUES (241, 48);
INSERT INTO Book_Categories VALUES (241, 172);
INSERT INTO Book_Categories VALUES (242, 177);
INSERT INTO Book_Categories VALUES (242, 39);
INSERT INTO Book_Categories VALUES (242, 70);
INSERT INTO Book_Categories VALUES (242, 16);
INSERT INTO Book_Categories VALUES (243, 242);
INSERT INTO Book_Categories VALUES (243, 44);
INSERT INTO Book_Categories VALUES (244, 60);
INSERT INTO Book_Categories VALUES (244, 57);
INSERT INTO Book_Categories VALUES (244, 243);
INSERT INTO Book_Categories VALUES (245, 16);
INSERT INTO Book_Categories VALUES (245, 55);
INSERT INTO Book_Categories VALUES (245, 57);
INSERT INTO Book_Categories VALUES (245, 4);
INSERT INTO Book_Categories VALUES (245, 87);
INSERT INTO Book_Categories VALUES (246, 244);
INSERT INTO Book_Categories VALUES (246, 70);
INSERT INTO Book_Categories VALUES (246, 163);
INSERT INTO Book_Categories VALUES (246, 44);
INSERT INTO Book_Categories VALUES (247, 25);
INSERT INTO Book_Categories VALUES (247, 4);
INSERT INTO Book_Categories VALUES (248, 72);
INSERT INTO Book_Categories VALUES (248, 29);
INSERT INTO Users VALUES (DEFAULT, 'admin', 'admin@admin.com', '$argon2id$v=19$m=65536,t=3,p=4$pLRWSklpDQEgBEColfLe2w$3Ji+/asG//8gzv8C6uGvq2f5jJliFZFxrSoURf+yYPs', TRUE);